import { createConnection } from "mysql2/promise";
import * as dotenv from "dotenv";
dotenv.config();

const DB_URL = process.env.DATABASE_URL;
if (!DB_URL) throw new Error("DATABASE_URL not set");

const schools = [
  // ── UK (20) ────────────────────────────────────────────────────────────────────
  {
    name: "Oxford Aviation Academy (CAE)",
    country: "United Kingdom",
    city: "Oxford",
    airport: "Oxford Airport (EGTK)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: false,
    priceRange: "£100,000–£130,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "easyJet, Ryanair, TUI",
    website: "https://www.cae.com/civil-aviation/aviation-training-network/cae-oxford/",
    description: "One of the world's largest aviation training organisations. Offers integrated and modular ATPL programmes with strong airline placement records.",
    active: true
  },
  {
    name: "L3Harris Airline Academy",
    country: "United Kingdom",
    city: "Crawley",
    airport: "London Gatwick (EGKK)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: false,
    priceRange: "£90,000–£120,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "British Airways, easyJet",
    website: "https://www.l3commercialaviation.com/",
    description: "Renowned for its integrated ATPL and MPL programmes. State-of-the-art simulators and training facilities.",
    active: true
  },
  {
    name: "Skyborne Airline Academy",
    country: "United Kingdom",
    city: "Gloucester",
    airport: "Gloucestershire Airport (EGBJ)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: false,
    priceRange: "£85,000–£105,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "easyJet, Loganair",
    website: "https://skyborne.com/",
    description: "Modern academy offering both integrated and modular routes with a focus on airline-focused training methodologies.",
    active: true
  },
  {
    name: "FTEJerez (UK Campus / Operations)",
    country: "United Kingdom",
    city: "Various",
    airport: "Various",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "£100,000–£120,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "British Airways, Aer Lingus, easyJet",
    website: "https://www.ftejerez.com/",
    description: "While based in Spain, FTEJerez is a major provider for UK cadets and airlines, offering premium integrated training.",
    active: true
  },
  {
    name: "Leading Edge Aviation",
    country: "United Kingdom",
    city: "Oxford",
    airport: "Oxford Airport (EGTK)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "£80,000–£105,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Wizz Air",
    website: "https://leadingedgeaviation.com/",
    description: "A forward-thinking academy offering integrated (LEAP) and modular courses, utilizing modern Diamond aircraft.",
    active: true
  },
  {
    name: "Booker Aviation",
    country: "United Kingdom",
    city: "High Wycombe",
    airport: "Wycombe Air Park (EGTB)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£50,000–£70,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://www.bookeraviation.aero/",
    description: "Highly respected modular training provider offering PPL through to CPL/ME/IR.",
    active: true
  },
  {
    name: "Stapleford Flight Centre",
    country: "United Kingdom",
    city: "Romford",
    airport: "Stapleford Aerodrome (EGSG)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£50,000–£70,000",
    financeAvailable: "no",
    accommodationAvailable: "yes",
    airlinePartnerships: "",
    website: "https://www.flysfc.com/",
    description: "One of the UK's oldest and most established modular flight schools, offering comprehensive commercial training.",
    active: true
  },
  {
    name: "Bristol Groundschool",
    country: "United Kingdom",
    city: "Clevedon",
    airport: "N/A (Ground School)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: false,
    priceRange: "£2,000–£3,000 (Theory only)",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://www.bristol.gs/",
    description: "Europe's leading provider of ATPL distance learning and ground school for modular students.",
    active: true
  },
  {
    name: "ACS Flight Training",
    country: "United Kingdom",
    city: "Perth",
    airport: "Perth Airport (EGPT)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£55,000–£75,000",
    financeAvailable: "no",
    accommodationAvailable: "yes",
    airlinePartnerships: "Loganair",
    website: "https://www.acsflighttraining.co.uk/",
    description: "Scotland's premier commercial flight training academy, offering modular ATPL courses.",
    active: true
  },
  {
    name: "BCFT (Blackbushe Centre of Flight Training)",
    country: "United Kingdom",
    city: "Camberley",
    airport: "Blackbushe Airport (EGLK)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£50,000–£70,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://www.bcft.aero/",
    description: "Provides high-quality modular commercial flight training in the south of England.",
    active: true
  },
  {
    name: "Tayside Aviation",
    country: "United Kingdom",
    city: "Dundee",
    airport: "Dundee Airport (EGPN)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£60,000–£80,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Loganair",
    website: "https://www.taysideaviation.com/",
    description: "Long-established Scottish flight school offering degree programmes in conjunction with local universities.",
    active: true
  },
  {
    name: "Almat Flying Academy",
    country: "United Kingdom",
    city: "Coventry",
    airport: "Coventry Airport (EGBE)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£45,000–£65,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://almat.co.uk/",
    description: "Friendly modular flight school based in the Midlands.",
    active: true
  },
  {
    name: "Aeros Flight Training",
    country: "United Kingdom",
    city: "Various (Gloucester, Coventry, Cardiff)",
    airport: "Various",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£55,000–£75,000",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://www.aeros.co.uk/",
    description: "Multi-base modular training provider offering the 'Fastrack' commercial route.",
    active: true
  },
  {
    name: "MFTA (Multi-Flight Training Academy)",
    country: "United Kingdom",
    city: "Bournemouth",
    airport: "Bournemouth Airport (EGHH)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£50,000–£70,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://www.mfta.co.uk/",
    description: "Specialists in modular commercial flight training on the south coast.",
    active: true
  },
  {
    name: "Ravenair",
    country: "United Kingdom",
    city: "Liverpool",
    airport: "Liverpool John Lennon Airport (EGGP)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£50,000–£70,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://www.ravenair.co.uk/",
    description: "Provides modular training in a busy international airport environment.",
    active: true
  },
  {
    name: "Lomac Aviators",
    country: "United Kingdom",
    city: "Liverpool",
    airport: "Liverpool John Lennon Airport (EGGP)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£45,000–£65,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://www.lomacaviators.com/",
    description: "Established modular training provider in the North West.",
    active: true
  },
  {
    name: "Central Flight Training",
    country: "United Kingdom",
    city: "Tatenhill",
    airport: "Tatenhill Airfield (EGBM)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£45,000–£65,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://www.centralflighttraining.com/",
    description: "Offers cost-effective modular commercial training.",
    active: true
  },
  {
    name: "Westair Flying School",
    country: "United Kingdom",
    city: "Blackpool",
    airport: "Blackpool Airport (EGNH)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£45,000–£65,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://www.westair.uk.com/",
    description: "Family-run business offering PPL and commercial modular training.",
    active: true
  },
  // Set to inactive as requested
  {
    name: "FTA Global Brighton",
    country: "United Kingdom",
    city: "Brighton",
    airport: "Shoreham Airport (EGKA)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "£80,000–£100,000",
    financeAvailable: "unknown",
    accommodationAvailable: "unknown",
    airlinePartnerships: "",
    website: "",
    description: "School ceased operations.",
    active: false
  },
  {
    name: "Acron UK",
    country: "United Kingdom",
    city: "London",
    airport: "N/A",
    integratedAtpl: false,
    modularAtpl: false,
    ppl: false,
    priceRange: "",
    financeAvailable: "unknown",
    accommodationAvailable: "unknown",
    airlinePartnerships: "",
    website: "",
    description: "No longer active.",
    active: false
  },

  // ── USA (15) ───────────────────────────────────────────────────────────────────
  {
    name: "ATP Flight School",
    country: "United States",
    city: "Various (70+ locations)",
    airport: "Various",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$90,000–$110,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "United, Delta, American, SkyWest",
    website: "https://atpflightschool.com/",
    description: "The largest flight school in the US, known for its fast-track Airline Career Pilot Program.",
    active: true
  },
  {
    name: "Embry-Riddle Aeronautical University",
    country: "United States",
    city: "Daytona Beach / Prescott",
    airport: "DAB / PRC",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: true,
    priceRange: "$150,000–$250,000 (incl. degree)",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Delta, United, JetBlue",
    website: "https://erau.edu/",
    description: "The 'Harvard of the Sky'. Offers Part 141 training integrated with a 4-year degree.",
    active: true
  },
  {
    name: "CAE Phoenix",
    country: "United States",
    city: "Phoenix",
    airport: "Falcon Field (KDFF)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$90,000–$120,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Southwest, American",
    website: "https://www.cae.com/",
    description: "CAE's primary US academy, offering excellent weather year-round for fast-track training.",
    active: true
  },
  {
    name: "AeroGuard Flight Training Center",
    country: "United States",
    city: "Phoenix",
    airport: "Deer Valley (KDVT)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$90,000–$110,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "SkyWest, Cathay Pacific",
    website: "https://www.flyaeroguard.com/",
    description: "Focuses on high-quality, airline-oriented training for both domestic and international cadets.",
    active: true
  },
  {
    name: "L3Harris Flight Academy",
    country: "United States",
    city: "Sanford",
    airport: "Orlando Sanford (KSFB)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$95,000–$115,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "United, Delta, American",
    website: "https://www.l3commercialaviation.com/",
    description: "Major training provider in Florida with a massive fleet and strong airline connections.",
    active: true
  },
  {
    name: "University of North Dakota (UND)",
    country: "United States",
    city: "Grand Forks",
    airport: "Grand Forks (KGFK)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: true,
    priceRange: "$120,000–$180,000 (incl. degree)",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Delta, United",
    website: "https://aero.und.edu/",
    description: "One of the most respected collegiate aviation programs in the world. Qualifies for R-ATP.",
    active: true
  },
  {
    name: "Purdue University",
    country: "United States",
    city: "West Lafayette",
    airport: "Purdue University Airport (KLAF)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: true,
    priceRange: "$120,000–$180,000 (incl. degree)",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Republic Airways, Envoy",
    website: "https://polytechnic.purdue.edu/aviation-and-transportation-technology",
    description: "Prestigious university aviation program with a strong alumni network.",
    active: true
  },
  {
    name: "United Aviate Academy",
    country: "United States",
    city: "Goodyear",
    airport: "Phoenix Goodyear (KGYR)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: true,
    priceRange: "$70,000–$90,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "United Airlines",
    website: "https://unitedaviate.com/academy/",
    description: "United Airlines' wholly-owned flight school, designed to funnel cadets directly to the airline.",
    active: true
  },
  {
    name: "Spartan College of Aeronautics",
    country: "United States",
    city: "Tulsa",
    airport: "Tulsa Riverside (KRVS)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$80,000–$100,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "SkyWest, American",
    website: "https://www.spartan.edu/",
    description: "Historic aviation college offering both flight training and maintenance programs.",
    active: true
  },
  {
    name: "US Aviation Academy",
    country: "United States",
    city: "Denton",
    airport: "Denton Enterprise (KDTO)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$85,000–$105,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Envoy, PSA",
    website: "https://www.usaviationacademy.com/",
    description: "Large Texas-based academy offering accelerated Part 141 programs.",
    active: true
  },
  {
    name: "Epic Flight Academy",
    country: "United States",
    city: "New Smyrna Beach",
    airport: "New Smyrna Beach (KEVB)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$80,000–$100,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "United, Southern Airways",
    website: "https://epicflightacademy.com/",
    description: "Florida-based school popular with both domestic and international students.",
    active: true
  },
  {
    name: "Sierra Academy of Aeronautics",
    country: "United States",
    city: "Atwater",
    airport: "Castle Airport (KMER)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$80,000–$100,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Various",
    website: "https://sierraacademy.com/",
    description: "California-based academy with a long history of training international cadets.",
    active: true
  },
  {
    name: "FlightSafety Academy",
    country: "United States",
    city: "Vero Beach",
    airport: "Vero Beach (KVRB)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$90,000–$110,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Various",
    website: "https://www.flightsafety.com/",
    description: "Renowned global training provider's ab-initio academy in Florida.",
    active: true
  },
  {
    name: "Blue Line Aviation",
    country: "United States",
    city: "Smithfield",
    airport: "Johnston Regional (KJNX)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$85,000–$105,000",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "Various",
    website: "https://www.bluelineaviation.com/",
    description: "Fast-growing academy in North Carolina with a modern Diamond fleet.",
    active: true
  },
  {
    name: "Coast Flight Training",
    country: "United States",
    city: "San Diego",
    airport: "Montgomery Field (KMYF)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$85,000–$105,000",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "American Airlines",
    website: "https://coastflight.com/",
    description: "Partner in the American Airlines Cadet Academy, based in sunny Southern California.",
    active: true
  },

  // ── Australia (10) ─────────────────────────────────────────────────────────────
  {
    name: "UNSW Aviation",
    country: "Australia",
    city: "Sydney",
    airport: "Bankstown (YSBK)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: true,
    priceRange: "$130,000–$150,000 AUD",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "QantasLink",
    website: "https://www.aviation.unsw.edu.au/",
    description: "Top-tier university aviation program offering a Bachelor of Aviation (Flying) with FEE-HELP.",
    active: true
  },
  {
    name: "CAE Melbourne",
    country: "Australia",
    city: "Melbourne",
    airport: "Moorabbin (YMMB)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$120,000–$140,000 AUD",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Jetstar, Virgin Australia",
    website: "https://www.cae.com/",
    description: "Major training hub for Australian airlines and international cadets.",
    active: true
  },
  {
    name: "Flight Training Adelaide (FTA)",
    country: "Australia",
    city: "Adelaide",
    airport: "Parafield (YPAD)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$120,000–$140,000 AUD",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Cathay Pacific, QantasLink",
    website: "https://www.flyfta.com/",
    description: "World-renowned academy, heavily utilized by Asian and Australian carriers for cadet training.",
    active: true
  },
  {
    name: "RMIT University",
    country: "Australia",
    city: "Melbourne",
    airport: "Point Cook (YMPC)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: true,
    priceRange: "$130,000–$150,000 AUD",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Qantas",
    website: "https://www.rmit.edu.au/",
    description: "Offers a Bachelor of Applied Science (Aviation) combined with flight training.",
    active: true
  },
  {
    name: "Griffith University",
    country: "Australia",
    city: "Brisbane",
    airport: "Archerfield (YBAF)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: true,
    priceRange: "$130,000–$150,000 AUD",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Qantas",
    website: "https://www.griffith.edu.au/",
    description: "Highly respected Queensland university offering degree-integrated flight training.",
    active: true
  },
  {
    name: "Basair Aviation College",
    country: "Australia",
    city: "Sydney / Brisbane",
    airport: "Bankstown / Archerfield",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$100,000–$120,000 AUD",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "Various",
    website: "https://www.basair.com.au/",
    description: "One of Australia's largest independent flying colleges, offering VET FEE-HELP.",
    active: true
  },
  {
    name: "Air Gold Coast",
    country: "Australia",
    city: "Gold Coast",
    airport: "Gold Coast (YBCG)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "$90,000–$110,000 AUD",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://www.airgoldcoast.com.au/",
    description: "Provides high-quality modular and diploma courses in a great location.",
    active: true
  },
  {
    name: "Moorabbin Aviation Services",
    country: "Australia",
    city: "Melbourne",
    airport: "Moorabbin (YMMB)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "$90,000–$110,000 AUD",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://www.moorabbinaviation.com.au/",
    description: "Established modular school offering comprehensive CPL and MEIR training.",
    active: true
  },
  {
    name: "Swinburne University",
    country: "Australia",
    city: "Melbourne",
    airport: "Moorabbin (YMMB)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: true,
    priceRange: "$130,000–$150,000 AUD",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Jetstar",
    website: "https://www.swinburne.edu.au/",
    description: "Offers a Bachelor of Aviation with flying training conducted by CAE.",
    active: true
  },
  {
    name: "Soar Aviation",
    country: "Australia",
    city: "Melbourne",
    airport: "Moorabbin (YMMB)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$90,000–$110,000 AUD",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://soaraviation.com.au/",
    description: "Fast-growing academy offering diploma-level flight training.",
    active: true
  },

  // ── Canada (10) ────────────────────────────────────────────────────────────────
  {
    name: "Seneca College",
    country: "Canada",
    city: "Toronto",
    airport: "Peterborough (CYPQ)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: true,
    priceRange: "$90,000–$110,000 CAD",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Air Canada, Jazz",
    website: "https://www.senecacollege.ca/",
    description: "Canada's premier publicly-funded aviation degree program. Highly competitive.",
    active: true
  },
  {
    name: "Sault College",
    country: "Canada",
    city: "Sault Ste. Marie",
    airport: "Sault Ste. Marie (CYAM)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: true,
    priceRange: "$80,000–$100,000 CAD",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Air Canada Jazz",
    website: "https://www.saultcollege.ca/",
    description: "Respected college program offering subsidized flight training for Canadian residents.",
    active: true
  },
  {
    name: "Mount Royal University",
    country: "Canada",
    city: "Calgary",
    airport: "Springbank (CYBW)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: true,
    priceRange: "$100,000–$120,000 CAD",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "WestJet, Air Canada",
    website: "https://www.mtroyal.ca/",
    description: "Offers a highly regarded Aviation Diploma integrated with commercial flight training.",
    active: true
  },
  {
    name: "Brampton Flight Centre",
    country: "Canada",
    city: "Brampton",
    airport: "Brampton (CNC3)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$80,000–$100,000 CAD",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "Jazz Aviation",
    website: "https://www.bramptonflightcentre.com/",
    description: "One of Canada's largest and oldest flight schools, offering college-partnered programs.",
    active: true
  },
  {
    name: "Pacific Flying Club",
    country: "Canada",
    city: "Vancouver",
    airport: "Boundary Bay (CZBB)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$80,000–$100,000 CAD",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "WestJet",
    website: "https://www.pacificflying.com/",
    description: "Major West Coast training provider offering diploma programs with BCIT.",
    active: true
  },
  {
    name: "Moncton Flight College",
    country: "Canada",
    city: "Moncton",
    airport: "Greater Moncton (CYQM)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$85,000–$105,000 CAD",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Air Canada Jazz",
    website: "https://mfc.nb.ca/",
    description: "The largest private flight school in Canada, training cadets from around the world.",
    active: true
  },
  {
    name: "Waterloo Wellington Flight Centre",
    country: "Canada",
    city: "Waterloo",
    airport: "Region of Waterloo (CYKF)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$80,000–$100,000 CAD",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "Sunwing",
    website: "https://wwfc.ca/",
    description: "Partners with the University of Waterloo and Conestoga College for degree/diploma programs.",
    active: true
  },
  {
    name: "Okanagan College",
    country: "Canada",
    city: "Kelowna",
    airport: "Kelowna (CYLW)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: true,
    priceRange: "$80,000–$100,000 CAD",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Encore",
    website: "https://www.okanagan.bc.ca/",
    description: "Offers a Commercial Aviation Diploma with flight training provided by Southern Interior Flight Centre.",
    active: true
  },
  {
    name: "Algonquin College",
    country: "Canada",
    city: "Ottawa",
    airport: "Ottawa (CYOW)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: true,
    priceRange: "$85,000–$105,000 CAD",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Jazz",
    website: "https://www.algonquincollege.com/",
    description: "Aviation Management diploma program providing comprehensive flight and academic training.",
    active: true
  },
  {
    name: "Sky Wings Aviation",
    country: "Canada",
    city: "Red Deer",
    airport: "Red Deer (CYQF)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "$70,000–$90,000 CAD",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://www.skywings.com/",
    description: "Respected modular flight school in Alberta.",
    active: true
  },

  // ── Europe (5) ─────────────────────────────────────────────────────────────────
  {
    name: "European Flight Academy (Lufthansa)",
    country: "Germany",
    city: "Bremen",
    airport: "Bremen (EDDW)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "€80,000–€110,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Lufthansa Group",
    website: "https://www.european-flight-academy.com/",
    description: "Lufthansa Group's official flight school. Highly selective with deferred payment options.",
    active: true
  },
  {
    name: "ENAC",
    country: "France",
    city: "Toulouse",
    airport: "Toulouse Lasbordes (LFCL)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "State Sponsored (Free)",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Air France",
    website: "https://www.enac.fr/",
    description: "The French National Civil Aviation University. Free for those who pass the highly competitive concours.",
    active: true
  },
  {
    name: "FTEJerez",
    country: "Spain",
    city: "Jerez",
    airport: "Jerez (LEJR)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "€110,000–€130,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "British Airways, easyJet, Aer Lingus",
    website: "https://www.ftejerez.com/",
    description: "Premium European integrated academy with excellent weather and strong airline ties.",
    active: true
  },
  {
    name: "CAE Madrid",
    country: "Spain",
    city: "Madrid",
    airport: "Cuatro Vientos (LECU)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: false,
    priceRange: "€100,000–€120,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Vueling, Volotea",
    website: "https://www.cae.com/",
    description: "CAE's primary Southern European base, offering great flying weather.",
    active: true
  },
  {
    name: "Bartolini Air",
    country: "Poland",
    city: "Lodz",
    airport: "Lodz (EPLL)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "€60,000–€80,000",
    financeAvailable: "no",
    accommodationAvailable: "yes",
    airlinePartnerships: "Ryanair",
    website: "https://bartoliniair.com/",
    description: "Highly regarded, cost-effective academy in Poland, official partner of the Ryanair Mentored Programme.",
    active: true
  },

  // ── UAE & South Africa (5) ─────────────────────────────────────────────────────
  {
    name: "Emirates Flight Training Academy",
    country: "UAE",
    city: "Dubai",
    airport: "Al Maktoum (OMDW)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "Sponsored (Nationals) / $180,000 (Intl)",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Emirates",
    website: "https://www.emiratesflighttrainingacademy.com/",
    description: "State-of-the-art facility built by Emirates to train their future pilots.",
    active: true
  },
  {
    name: "Alpha Aviation Academy",
    country: "UAE",
    city: "Sharjah",
    airport: "Sharjah (OMSJ)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "$140,000–$160,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Air Arabia",
    website: "https://www.alphaaviationacademy.com/",
    description: "Specializes in MPL training in partnership with Air Arabia.",
    active: true
  },
  {
    name: "43 Air School",
    country: "South Africa",
    city: "Port Alfred",
    airport: "Port Alfred (FAPA)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "$60,000–$80,000 USD",
    financeAvailable: "no",
    accommodationAvailable: "yes",
    airlinePartnerships: "Various African Carriers",
    website: "https://www.43airschool.com/",
    description: "Africa's premier flight school, training cadets from across the continent and globally.",
    active: true
  },
  {
    name: "Loutzavia",
    country: "South Africa",
    city: "Pretoria",
    airport: "Wonderboom (FAWB)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "$50,000–$70,000 USD",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://www.loutzavia.co.za/",
    description: "Well-established modular flight school in South Africa.",
    active: true
  },
  {
    name: "Blue Chip Flight School",
    country: "South Africa",
    city: "Pretoria",
    airport: "Wonderboom (FAWB)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "$50,000–$70,000 USD",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: "",
    website: "https://bluechipflightschool.co.za/",
    description: "Offers high-quality PPL and CPL training in the busy Gauteng airspace.",
    active: true
  }
];

async function seedSchools() {
  console.log("Connecting to database...");
  const connection = await createConnection(DB_URL);
  try {
    console.log("Clearing existing schools...");
    await connection.execute("DELETE FROM flight_schools");
    
    console.log(`Inserting ${schools.length} schools...`);
    for (const school of schools) {
      await connection.execute(
        `INSERT INTO flight_schools (name, country, city, airport, integrated_atpl, modular_atpl, ppl, price_range, finance_available, accommodation_available, airline_partnerships, website, description, active)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          school.name,
          school.country,
          school.city,
          school.airport,
          school.integratedAtpl,
          school.modularAtpl,
          school.ppl,
          school.priceRange,
          school.financeAvailable,
          school.accommodationAvailable,
          school.airlinePartnerships,
          school.website,
          school.description,
          school.active
        ]
      );
    }
    console.log("Schools seeded successfully!");
  } catch (error) {
    console.error("Error seeding schools:", error);
  } finally {
    await connection.end();
  }
}

seedSchools();
