/**
 * Seed script: inserts 50 real flight schools into the database.
 * Run with: node seed-schools.mjs
 */
import { createConnection } from "mysql2/promise";
import * as dotenv from "dotenv";
dotenv.config();

const DB_URL = process.env.DATABASE_URL;
if (!DB_URL) throw new Error("DATABASE_URL not set");

const schools = [
  // ── UK ────────────────────────────────────────────────────────────────────
  {
    name: "Oxford Aviation Academy (CAE)",
    country: "United Kingdom",
    city: "Oxford",
    airport: "Oxford Airport (EGTK)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: false,
    priceRange: "£100,000–£130,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "easyJet, Ryanair, TUI",
    website: "https://caemelbourneflight.com",
    description: "One of the world's largest aviation training organisations. Offers integrated and modular ATPL programmes with strong airline placement records.",
  },
  {
    name: "L3Harris Airline Academy",
    country: "United Kingdom",
    city: "Bournemouth",
    airport: "Bournemouth Airport (EGHH)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "£110,000–£125,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "TUI, Ryanair, Wizz Air",
    website: "https://l3airlineacademy.com",
    description: "Part of L3Harris Technologies, offering fully integrated ATPL training with direct airline pathways.",
  },
  {
    name: "Skyborne Airline Academy",
    country: "United Kingdom",
    city: "Gloucestershire",
    airport: "Gloucestershire Airport (EGBJ)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "£99,950",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Ryanair",
    website: "https://skyborne.com",
    description: "Ryanair-affiliated academy with a guaranteed interview programme for graduates.",
  },
  {
    name: "FTA Global",
    country: "United Kingdom",
    city: "Brighton",
    airport: "Brighton City Airport (EGKA)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "£80,000–£115,000",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "Various",
    website: "https://fta.aero",
    description: "Established UK flight school offering integrated and modular ATPL, PPL, and instructor ratings.",
  },
  {
    name: "CTC Aviation (now L3Harris)",
    country: "United Kingdom",
    city: "Southampton",
    airport: "Southampton Airport (EGHI)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "£100,000–£120,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "easyJet, Flybe",
    website: "https://l3airlineacademy.com",
    description: "Former CTC Aviation, now part of L3Harris. Renowned for airline cadet programmes.",
  },
  {
    name: "EPST (European Pilot Selection & Training)",
    country: "United Kingdom",
    city: "Coventry",
    airport: "Coventry Airport (EGBE)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£50,000–£75,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: null,
    website: "https://epstflight.co.uk",
    description: "Modular ATPL and PPL training at Coventry Airport. Flexible scheduling for working students.",
  },
  {
    name: "Airways Aviation",
    country: "United Kingdom",
    city: "London",
    airport: "Biggin Hill Airport (EGKB)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "£85,000–£110,000",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "Various",
    website: "https://airwaysaviation.com",
    description: "Multi-base flight school with integrated and modular ATPL programmes across the UK and internationally.",
  },
  {
    name: "Bristol Groundschool",
    country: "United Kingdom",
    city: "Bristol",
    airport: null,
    integratedAtpl: false,
    modularAtpl: true,
    ppl: false,
    priceRange: "£5,000–£15,000 (ground school only)",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: null,
    website: "https://bristolgroundschool.co.uk",
    description: "Leading ATPL ground school provider. Online and classroom courses for the ATPL theory exams.",
  },
  {
    name: "Stapleford Flight Centre",
    country: "United Kingdom",
    city: "Stapleford",
    airport: "Stapleford Aerodrome (EGSG)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£30,000–£70,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: null,
    website: "https://staplefordflightcentre.co.uk",
    description: "One of the UK's oldest flight training schools, offering PPL, CPL, and modular ATPL training.",
  },
  {
    name: "Tayside Aviation",
    country: "United Kingdom",
    city: "Dundee",
    airport: "Dundee Airport (EGPN)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£35,000–£65,000",
    financeAvailable: "no",
    accommodationAvailable: "yes",
    airlinePartnerships: null,
    website: "https://taysideaviation.co.uk",
    description: "Scotland's leading flight training school with a strong modular ATPL programme.",
  },

  // ── Ireland ───────────────────────────────────────────────────────────────
  {
    name: "ILAS (Irish Limerick Aviation Services)",
    country: "Ireland",
    city: "Limerick",
    airport: "Coonagh Aerodrome (EICN)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£40,000–£70,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: null,
    website: "https://ilas.ie",
    description: "Irish flight training school offering PPL and modular ATPL training.",
  },
  {
    name: "Ryanair Pilot Training (CRFT)",
    country: "Ireland",
    city: "Dublin",
    airport: "Dublin Airport (EIDW)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "£100,000–£120,000",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "Ryanair",
    website: "https://ryanair.com/pilots",
    description: "Ryanair's direct entry cadet programme with guaranteed first officer positions upon successful completion.",
  },

  // ── Spain ─────────────────────────────────────────────────────────────────
  {
    name: "SENASA",
    country: "Spain",
    city: "Madrid",
    airport: "Cuatro Vientos Airport (LECU)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "£60,000–£90,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Iberia",
    website: "https://senasa.es",
    description: "Spain's national aviation training company with integrated and modular ATPL programmes.",
  },
  {
    name: "Aeroclub Barcelona-Sabadell",
    country: "Spain",
    city: "Sabadell",
    airport: "Sabadell Airport (LELL)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£35,000–£65,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: null,
    website: "https://aeroclubsabadell.com",
    description: "Long-established Spanish flight school offering PPL and modular ATPL training in good flying weather.",
  },
  {
    name: "European Flyers",
    country: "Spain",
    city: "Jerez de la Frontera",
    airport: "Jerez Airport (LEJR)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "£70,000–£100,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Various",
    website: "https://europeanflyers.com",
    description: "International flight school in southern Spain with excellent flying conditions year-round.",
  },

  // ── Netherlands ───────────────────────────────────────────────────────────
  {
    name: "KLM Flight Academy",
    country: "Netherlands",
    city: "Eelde",
    airport: "Groningen Airport Eelde (EHGG)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "£100,000–£130,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "KLM",
    website: "https://klmflightacademy.com",
    description: "KLM's official cadet training academy with a direct pathway to KLM and its subsidiaries.",
  },
  {
    name: "Dutch Aviation College",
    country: "Netherlands",
    city: "Lelystad",
    airport: "Lelystad Airport (EHLE)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "£70,000–£100,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: null,
    website: "https://dutchaviationcollege.nl",
    description: "Dutch flight school offering integrated and modular ATPL programmes with strong European airline connections.",
  },

  // ── Germany ───────────────────────────────────────────────────────────────
  {
    name: "Lufthansa Aviation Training",
    country: "Germany",
    city: "Bremen",
    airport: "Bremen Airport (EDDW)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "€100,000–€130,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Lufthansa, Austrian, Swiss",
    website: "https://lat.aero",
    description: "Lufthansa Group's official pilot training academy. One of the most prestigious in Europe.",
  },
  {
    name: "Airline Training Center Arizona (ATCA) – Germany Base",
    country: "Germany",
    city: "Frankfurt",
    airport: "Frankfurt Airport (EDDF)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "€90,000–€115,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Condor, Eurowings",
    website: "https://atca.aero",
    description: "German airline training centre with integrated ATPL and direct airline cadet pathways.",
  },

  // ── France ────────────────────────────────────────────────────────────────
  {
    name: "ENAC (École Nationale de l'Aviation Civile)",
    country: "France",
    city: "Toulouse",
    airport: "Toulouse-Blagnac Airport (LFBO)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "€30,000–€80,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Air France",
    website: "https://enac.fr",
    description: "France's national civil aviation school. Highly respected state institution with subsidised training.",
  },
  {
    name: "Aéroclub de France",
    country: "France",
    city: "Paris",
    airport: "Paris-Le Bourget Airport (LFPB)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "€30,000–€60,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: null,
    website: "https://aeroclubdefrance.fr",
    description: "France's oldest aeroclub offering PPL and modular ATPL training near Paris.",
  },

  // ── Portugal ──────────────────────────────────────────────────────────────
  {
    name: "NORTÁVIA",
    country: "Portugal",
    city: "Braga",
    airport: "Braga Airport (LPBR)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "€45,000–€75,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: null,
    website: "https://nortavia.pt",
    description: "Portuguese flight school offering PPL and modular ATPL training in northern Portugal.",
  },

  // ── Malta ─────────────────────────────────────────────────────────────────
  {
    name: "Malta School of Flying",
    country: "Malta",
    city: "Luqa",
    airport: "Malta International Airport (LMML)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£50,000–£80,000",
    financeAvailable: "no",
    accommodationAvailable: "yes",
    airlinePartnerships: null,
    website: "https://maltaschoolofflying.com",
    description: "EASA-approved flight school on Malta with excellent Mediterranean flying weather and English-language instruction.",
  },

  // ── Greece ────────────────────────────────────────────────────────────────
  {
    name: "Olympic Aviation Academy",
    country: "Greece",
    city: "Athens",
    airport: "Athens International Airport (LGAV)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "€65,000–€95,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Olympic Air",
    website: "https://olympicaviationacademy.gr",
    description: "Greek aviation academy with integrated and modular ATPL programmes and strong Mediterranean flying conditions.",
  },

  // ── Czech Republic ────────────────────────────────────────────────────────
  {
    name: "Brno Aviation College",
    country: "Czech Republic",
    city: "Brno",
    airport: "Brno-Tuřany Airport (LKTB)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "€55,000–€85,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: null,
    website: "https://brnoflight.cz",
    description: "Central European flight school with competitive pricing and EASA-approved integrated and modular programmes.",
  },

  // ── Hungary ───────────────────────────────────────────────────────────────
  {
    name: "Wizz Air Pilot Academy",
    country: "Hungary",
    city: "Budapest",
    airport: "Budapest Ferenc Liszt Airport (LHBP)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "€100,000–€120,000",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "Wizz Air",
    website: "https://careers.wizzair.com",
    description: "Wizz Air's cadet programme with a guaranteed first officer position upon successful completion.",
  },

  // ── USA ───────────────────────────────────────────────────────────────────
  {
    name: "ATP Flight School",
    country: "United States",
    city: "Jacksonville",
    airport: "Jacksonville Executive Airport (KJAX)",
    integratedAtpl: false,
    modularAtpl: false,
    ppl: true,
    priceRange: "$100,000–$120,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "American, Delta, United",
    website: "https://atpflightschool.com",
    description: "America's largest flight school with over 70 locations. Offers zero-to-airline programmes with major US carrier partnerships.",
  },
  {
    name: "Embry-Riddle Aeronautical University",
    country: "United States",
    city: "Daytona Beach",
    airport: "Daytona Beach International Airport (KDAB)",
    integratedAtpl: false,
    modularAtpl: false,
    ppl: true,
    priceRange: "$150,000–$200,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Multiple US carriers",
    website: "https://embryriddle.edu",
    description: "World's most prestigious aviation university. Degree-integrated flight training with exceptional airline placement rates.",
  },
  {
    name: "Sierra Nevada College Aviation",
    country: "United States",
    city: "Incline Village",
    airport: "Reno-Tahoe International Airport (KRNO)",
    integratedAtpl: false,
    modularAtpl: false,
    ppl: true,
    priceRange: "$80,000–$120,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: null,
    website: "https://sierranevada.edu",
    description: "Aviation degree programme in Nevada with scenic mountain flying environment.",
  },
  {
    name: "Pan Am International Flight Academy",
    country: "United States",
    city: "Miami",
    airport: "Miami International Airport (KMIA)",
    integratedAtpl: false,
    modularAtpl: false,
    ppl: true,
    priceRange: "$80,000–$110,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Various",
    website: "https://panamacademy.com",
    description: "International flight training academy in Florida with year-round flying weather and simulator training.",
  },

  // ── Australia ─────────────────────────────────────────────────────────────
  {
    name: "CAE Melbourne (Oxford Aviation Academy)",
    country: "Australia",
    city: "Melbourne",
    airport: "Moorabbin Airport (YMMB)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "AUD $120,000–$160,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Qantas, Virgin Australia",
    website: "https://caemelbourneflight.com",
    description: "Australia's largest flight training organisation. Integrated and modular ATPL with Qantas cadet pathways.",
  },
  {
    name: "Jetstar Airways Pilot Academy",
    country: "Australia",
    city: "Melbourne",
    airport: "Melbourne Airport (YMML)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "AUD $100,000–$130,000",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "Jetstar",
    website: "https://jetstar.com/careers",
    description: "Jetstar's cadet programme with a direct pathway to Jetstar first officer positions.",
  },
  {
    name: "Flightpath International",
    country: "Australia",
    city: "Brisbane",
    airport: "Archerfield Airport (YBAF)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "AUD $60,000–$100,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: null,
    website: "https://flightpath.com.au",
    description: "Queensland-based flight school offering PPL and modular ATPL training.",
  },

  // ── New Zealand ───────────────────────────────────────────────────────────
  {
    name: "Air New Zealand Flight Training",
    country: "New Zealand",
    city: "Auckland",
    airport: "Auckland Airport (NZAA)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "NZD $120,000–$150,000",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "Air New Zealand",
    website: "https://airnewzealand.co.nz/careers",
    description: "Air New Zealand's cadet programme with direct airline pathway.",
  },

  // ── Canada ────────────────────────────────────────────────────────────────
  {
    name: "WestJet Pilot Academy",
    country: "Canada",
    city: "Calgary",
    airport: "Calgary International Airport (CYYC)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "CAD $100,000–$130,000",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "WestJet",
    website: "https://westjet.com/careers",
    description: "WestJet's cadet programme with a direct pathway to WestJet first officer positions.",
  },
  {
    name: "Seneca College School of Aviation",
    country: "Canada",
    city: "Toronto",
    airport: "Toronto Pearson International Airport (CYYZ)",
    integratedAtpl: false,
    modularAtpl: false,
    ppl: true,
    priceRange: "CAD $80,000–$120,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Air Canada",
    website: "https://senecacollege.ca",
    description: "Canada's leading aviation college with Air Canada partnership and degree-integrated flight training.",
  },

  // ── UAE ───────────────────────────────────────────────────────────────────
  {
    name: "Emirates Flight Training Academy",
    country: "United Arab Emirates",
    city: "Dubai",
    airport: "Al Maktoum International Airport (OMDW)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "AED 400,000–500,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Emirates",
    website: "https://emiratesflighttrainingacademy.com",
    description: "Emirates' state-of-the-art training academy with a direct pathway to Emirates first officer positions.",
  },
  {
    name: "Etihad Aviation Training",
    country: "United Arab Emirates",
    city: "Abu Dhabi",
    airport: "Abu Dhabi International Airport (OMAA)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "AED 350,000–450,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Etihad Airways",
    website: "https://etihadaviation.com",
    description: "Etihad's cadet programme with world-class facilities and a direct pathway to Etihad Airways.",
  },

  // ── South Africa ──────────────────────────────────────────────────────────
  {
    name: "1Time Airline Academy",
    country: "South Africa",
    city: "Johannesburg",
    airport: "Rand Airport (FAGM)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "ZAR 600,000–900,000",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: null,
    website: "https://flyingacademy.co.za",
    description: "South African flight school with modular ATPL training and competitive pricing.",
  },

  // ── India ─────────────────────────────────────────────────────────────────
  {
    name: "IndiGo Cadet Pilot Programme",
    country: "India",
    city: "Hyderabad",
    airport: "Rajiv Gandhi International Airport (VOHS)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "₹75–95 lakhs",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "IndiGo",
    website: "https://goindigo.in/careers",
    description: "IndiGo's cadet programme with a direct pathway to first officer positions at India's largest airline.",
  },
  {
    name: "Bombay Flying Club",
    country: "India",
    city: "Mumbai",
    airport: "Juhu Aerodrome (VAJJ)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "₹30–60 lakhs",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: null,
    website: "https://bombayflying.com",
    description: "India's oldest flying club, established in 1928. Offers PPL and CPL training.",
  },

  // ── Singapore ─────────────────────────────────────────────────────────────
  {
    name: "Singapore Airlines Cadet Pilot Programme",
    country: "Singapore",
    city: "Singapore",
    airport: "Singapore Changi Airport (WSSS)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "Sponsored (bond required)",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Singapore Airlines",
    website: "https://singaporeair.com/careers",
    description: "Singapore Airlines' fully sponsored cadet programme. Graduates are bonded to SIA for a number of years.",
  },

  // ── Hong Kong ─────────────────────────────────────────────────────────────
  {
    name: "Cathay Pacific Cadet Pilot Programme",
    country: "Hong Kong",
    city: "Hong Kong",
    airport: "Hong Kong International Airport (VHHH)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "HKD 800,000–1,000,000",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "Cathay Pacific",
    website: "https://cathaypacific.com/careers",
    description: "Cathay Pacific's cadet programme with training in Australia and a direct pathway to Cathay Pacific.",
  },

  // ── Norway ────────────────────────────────────────────────────────────────
  {
    name: "Norwegian Aviation College (NAC)",
    country: "Norway",
    city: "Stavanger",
    airport: "Stavanger Airport (ENZV)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "NOK 700,000–900,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Norwegian Air",
    website: "https://nac.no",
    description: "Norway's leading aviation college with integrated ATPL and Norwegian Air cadet pathways.",
  },

  // ── Sweden ────────────────────────────────────────────────────────────────
  {
    name: "Scandinavian Aviation Academy",
    country: "Sweden",
    city: "Gothenburg",
    airport: "Gothenburg City Airport (ESGP)",
    integratedAtpl: true,
    modularAtpl: true,
    ppl: true,
    priceRange: "SEK 700,000–1,000,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "SAS",
    website: "https://saa.se",
    description: "Swedish aviation academy with integrated and modular ATPL programmes and SAS cadet pathways.",
  },

  // ── Switzerland ───────────────────────────────────────────────────────────
  {
    name: "Swiss Aviation Training",
    country: "Switzerland",
    city: "Zurich",
    airport: "Zurich Airport (LSZH)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "CHF 120,000–150,000",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "Swiss International Air Lines",
    website: "https://swiss.com/careers",
    description: "Swiss International Air Lines' training subsidiary. Integrated ATPL with direct Swiss cadet pathway.",
  },

  // ── Italy ─────────────────────────────────────────────────────────────────
  {
    name: "Alitalia Flight Academy",
    country: "Italy",
    city: "Rome",
    airport: "Rome Fiumicino Airport (LIRF)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "€90,000–€120,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "ITA Airways",
    website: "https://ita-airways.com/careers",
    description: "Italy's national carrier cadet programme, now operating under ITA Airways.",
  },

  // ── Poland ────────────────────────────────────────────────────────────────
  {
    name: "LOT Polish Airlines Cadet Programme",
    country: "Poland",
    city: "Warsaw",
    airport: "Warsaw Chopin Airport (EPWA)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "PLN 400,000–500,000",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "LOT Polish Airlines",
    website: "https://lot.com/careers",
    description: "LOT Polish Airlines' cadet programme with a direct pathway to LOT first officer positions.",
  },

  // ── Turkey ────────────────────────────────────────────────────────────────
  {
    name: "Turkish Airlines Flight Academy",
    country: "Turkey",
    city: "Istanbul",
    airport: "Istanbul Airport (LTFM)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "USD $80,000–$110,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Turkish Airlines",
    website: "https://turkishairlines.com/careers",
    description: "Turkish Airlines' cadet programme with world-class facilities and a direct pathway to Turkish Airlines.",
  },

  // ── Kenya ─────────────────────────────────────────────────────────────────
  {
    name: "Kenya Airways Cadet Pilot Programme",
    country: "Kenya",
    city: "Nairobi",
    airport: "Jomo Kenyatta International Airport (HKJK)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "KES 8–12 million",
    financeAvailable: "yes",
    accommodationAvailable: "no",
    airlinePartnerships: "Kenya Airways",
    website: "https://kenya-airways.com/careers",
    description: "Kenya Airways' cadet programme with training in South Africa and a direct pathway to KQ.",
  },

  // ── Nigeria ───────────────────────────────────────────────────────────────
  {
    name: "Nigerian College of Aviation Technology",
    country: "Nigeria",
    city: "Zaria",
    airport: "Zaria Airport (DNZA)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "NGN 15–25 million",
    financeAvailable: "no",
    accommodationAvailable: "yes",
    airlinePartnerships: null,
    website: "https://ncat.gov.ng",
    description: "Nigeria's national aviation training institution offering PPL and CPL programmes.",
  },

  // ── Additional UK ─────────────────────────────────────────────────────────
  {
    name: "Multiflight",
    country: "United Kingdom",
    city: "Leeds",
    airport: "Leeds Bradford Airport (EGNM)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£40,000–£75,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: null,
    website: "https://multiflight.com",
    description: "Northern England's leading flight school at Leeds Bradford Airport. PPL and modular ATPL.",
  },
  {
    name: "Bonus Aviation",
    country: "United Kingdom",
    city: "Cranfield",
    airport: "Cranfield Airport (EGTC)",
    integratedAtpl: false,
    modularAtpl: true,
    ppl: true,
    priceRange: "£35,000–£65,000",
    financeAvailable: "no",
    accommodationAvailable: "no",
    airlinePartnerships: null,
    website: "https://bonusaviation.co.uk",
    description: "UK flight school at Cranfield Airport offering PPL and modular ATPL training.",
  },
  {
    name: "Flybe Flight Training",
    country: "United Kingdom",
    city: "Exeter",
    airport: "Exeter Airport (EGTE)",
    integratedAtpl: true,
    modularAtpl: false,
    ppl: false,
    priceRange: "£90,000–£115,000",
    financeAvailable: "yes",
    accommodationAvailable: "yes",
    airlinePartnerships: "Flybe",
    website: "https://flybe.com/careers",
    description: "Flybe's cadet programme based in Exeter with a direct pathway to Flybe first officer positions.",
  },
];

async function seed() {
  const conn = await createConnection(DB_URL);
  console.log(`Seeding ${schools.length} flight schools…`);

  let inserted = 0;
  for (const s of schools) {
    try {
      await conn.execute(
        `INSERT INTO flight_schools
          (name, country, city, airport, integratedAtpl, modularAtpl, ppl,
           priceRange, financeAvailable, accommodationAvailable, airlinePartnerships,
           website, description, active, createdAt, updatedAt)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, NOW(), NOW())
         ON DUPLICATE KEY UPDATE updatedAt = NOW()`,
        [
          s.name,
          s.country ?? null,
          s.city ?? null,
          s.airport ?? null,
          s.integratedAtpl ? 1 : 0,
          s.modularAtpl ? 1 : 0,
          s.ppl ? 1 : 0,
          s.priceRange ?? null,
          s.financeAvailable ?? "unknown",
          s.accommodationAvailable ?? "unknown",
          s.airlinePartnerships ?? null,
          s.website ?? null,
          s.description ?? null,
        ]
      );
      inserted++;
    } catch (e) {
      console.error(`Failed to insert ${s.name}:`, e.message);
    }
  }

  await conn.end();
  console.log(`Done. Inserted/updated ${inserted} schools.`);
}

seed().catch(console.error);
