// AUTO-GENERATED by gen_guides_data.py — do not edit manually
// Re-run the script to regenerate from the source GuidesIndex pages

export interface GuideEntry {
  title: string;
  description: string;
  href: string;
  time: string;
  category: string;
  emoji: string;
}

export interface CountryGuideConfig {
  label: string;
  flag: string;
  regulator: string;
  roadmapHref: string;
  cadetToolHref: string;
  medicalToolHref: string;
  calculatorHref: string;
  isThin: boolean;  // true = fewer than 20 guides, show 'more coming' notice
  guides: GuideEntry[];
}

export type SupportedCountry = 'uk' | 'us' | 'australia' | 'canada' | 'europe' | 'new-zealand' | 'south-africa' | 'uae';

export const GUIDES_BY_COUNTRY: Record<SupportedCountry, CountryGuideConfig> = {
  'uk': {
    label: 'United Kingdom',
    flag: '🇬🇧',
    regulator: 'CAA / EASA',
    roadmapHref: '/roadmap',
    cadetToolHref: '/tools/cadet-eligibility',
    medicalToolHref: '/tools/class-1-medical-check',
    calculatorHref: '/calculator',
    isThin: false,
    guides: [
  // ── Getting Started ──────────────────────────────────────────────────────────
  { title: "How to Become a Pilot", description: "A complete step-by-step guide from zero experience to your first airline job.", href: "/guides/how-to-become-a-pilot", time: "8 min read", category: "Getting Started", emoji: "🛫" },
  { title: "Pilot Training Timeline Guide", description: "How long does it take to become a pilot? Realistic timelines for every route.", href: "/guides/training-timeline", time: "5 min read", category: "Getting Started", emoji: "📅" },
  { title: "Am I Too Old to Become a Pilot?", description: "The honest answer on age limits, career runway, and whether training at 30, 40 or 50 makes sense.", href: "/guides/am-i-too-old-to-become-a-pilot", time: "6 min read", category: "Getting Started", emoji: "🎂" },
  { title: "Am I Ready to Start Pilot Training?", description: "8 questions to answer honestly before committing money to flight training.", href: "/guides/am-i-ready-to-start-pilot-training", time: "7 min read", category: "Getting Started", emoji: "✅" },
  { title: "Pilot Aptitude Test Preparation", description: "What the tests measure, how to prepare, and free resources — without paying £200 for a prep course.", href: "/guides/pilot-aptitude-test-preparation", time: "9 min read", category: "Getting Started", emoji: "🧠" },
  { title: "Pilot Aptitude Test UK", description: "Overview of UK airline aptitude tests, what each section measures, and how to practise effectively.", href: "/guides/pilot-aptitude-test-uk", time: "8 min read", category: "Getting Started", emoji: "🧩" },
  { title: "Pilot Lifestyle UK", description: "What life as a UK airline pilot actually looks like — rosters, bases, commuting, and work-life balance.", href: "/guides/pilot-lifestyle-uk", time: "7 min read", category: "Getting Started", emoji: "🌅" },

  // ── Costs & Finance ──────────────────────────────────────────────────────────
  { title: "Pilot Training Cost Guide", description: "A detailed breakdown of what pilot training costs in the UK.", href: "/guides/pilot-training-costs", time: "7 min read", category: "Costs & Finance", emoji: "💰" },
  { title: "How to Finance Pilot Training (2026)", description: "Every realistic funding option — HSBC pilot loan, cadet bonds, savings strategies, and what to avoid.", href: "/guides/how-to-finance-pilot-training-uk", time: "9 min read", category: "Costs & Finance", emoji: "🏦" },
  { title: "Pilot Training Over 40", description: "Is it worth training as a pilot in your 40s? Real numbers, ROI calculation, and what airlines think.", href: "/guides/pilot-training-over-40", time: "7 min read", category: "Costs & Finance", emoji: "📐" },
  { title: "Integrated vs Modular: Which is Actually Cheaper?", description: "A brutally honest breakdown of the real costs of pilot training. We compare the £100k+ integrated route against the £60k modular route.", href: "/guides/integrated-vs-modular-cost", time: "9 min read", category: "Costs & Finance", emoji: "🧮" },
  { title: "Finance Guide", description: "A complete guide to financing your pilot training — every option, every caveat.", href: "/guides/finance-guide", time: "8 min read", category: "Costs & Finance", emoji: "💼" },

  // ── Training Routes ──────────────────────────────────────────────────────────
  { title: "Integrated vs Modular ATPL", description: "The two main routes to an ATPL explained — and how to choose between them.", href: "/guides/integrated-vs-modular", time: "6 min read", category: "Training Routes", emoji: "⚖️" },
  { title: "Best Route to Becoming an Airline Pilot", description: "The fastest and most cost-effective paths from zero to a first officer seat.", href: "/guides/best-route-to-airline", time: "6 min read", category: "Training Routes", emoji: "🗺️" },
  { title: "RAF vs Civilian Pilot Training", description: "Honest comparison of military and civilian routes — costs, timelines, lifestyle, and career outcomes.", href: "/guides/raf-vs-civilian-pilot-training", time: "8 min read", category: "Training Routes", emoji: "🪖" },
  { title: "Best Flight Schools UK 2026", description: "Data-driven comparison of the UK's top flight schools — outcomes, costs, fleet, and what students say.", href: "/guides/best-flight-schools-uk-2026", time: "10 min read", category: "Training Routes", emoji: "🏫" },
  { title: "ATPL Theory Exams: Complete Guide", description: "All 14 subjects, pass rates, difficulty ratings, and the study strategies that work.", href: "/guides/atpl-theory-exams-uk", time: "10 min read", category: "Training Routes", emoji: "📚" },
  { title: "Hour Building for Pilots", description: "How to build your 200 hours cheaply and efficiently — best locations, aircraft, and strategies.", href: "/guides/hour-building-pilot-uk", time: "8 min read", category: "Training Routes", emoji: "⏱️" },
  { title: "Pilot Type Ratings UK 2026", description: "What type ratings are, what they cost, and whether to self-fund or wait for airline sponsorship.", href: "/guides/pilot-type-rating-uk", time: "7 min read", category: "Training Routes", emoji: "🛩️" },
  { title: "Private Pilot Licence (PPL) UK", description: "PPL requirements, costs (£8,000–£15,000), theory exams, and what you can do with a PPL.", href: "/guides/ppl-uk", time: "8 min read", category: "Training Routes", emoji: "🛩️" },
  { title: "Commercial Pilot Licence (CPL) UK", description: "CPL requirements, costs, what jobs it unlocks, and how it fits into the ATPL pathway.", href: "/guides/cpl-uk", time: "8 min read", category: "Training Routes", emoji: "📋" },
  { title: "Instrument Rating (IR) UK", description: "EASA IR vs UK IR vs EIR — requirements, costs, and why it's essential for an airline career.", href: "/guides/instrument-rating-uk", time: "8 min read", category: "Training Routes", emoji: "🧭" },
  { title: "Frozen ATPL UK: What It Is & How to Get One", description: "What a frozen ATPL is, the 14 theory subjects, how long it takes, and how to unfreeze it.", href: "/guides/frozen-atpl-uk", time: "9 min read", category: "Training Routes", emoji: "❄️" },
  { title: "How to Become a Flight Instructor (FI) UK", description: "FI rating requirements, costs, salary, and how instructing fits into the hour-building strategy.", href: "/guides/flight-instructor-uk", time: "8 min read", category: "Training Routes", emoji: "👨‍🏫" },
  { title: "MCC & JOC Course UK", description: "What MCC and JOC are, cost (£3,500–£8,000), duration, and which airlines require which.", href: "/guides/mcc-joc-uk", time: "7 min read", category: "Training Routes", emoji: "🤝" },

  // ── Medical ──────────────────────────────────────────────────────────────────
  { title: "Class 1 Medical Guide", description: "What the Class 1 Medical tests, how to pass it, and what to do with a health condition.", href: "/guides/class-1-medical", time: "5 min read", category: "Medical", emoji: "🩺" },
  { title: "Can I Become a Pilot with ADHD?", description: "The 2026 UK CAA rules on ADHD, medication, and the exact steps to get your Class 1 Medical.", href: "/guides/adhd-pilot-uk", time: "6 min read", category: "Medical", emoji: "🧠" },
  { title: "Class 1 Medical Disqualifiers", description: "What conditions disqualify you from a Class 1 medical — and which ones don't.", href: "/guides/class-1-medical-disqualifiers", time: "7 min read", category: "Medical", emoji: "❤️" },
  { title: "Pilot Eyesight Requirements UK", description: "Can you become a pilot with glasses or contacts? Class 1 vision standards and colour vision rules.", href: "/guides/pilot-eyesight-requirements-uk", time: "6 min read", category: "Medical", emoji: "👁️" },

  // ── Career ───────────────────────────────────────────────────────────────────
  { title: "Airline Pilot Salary Guide", description: "What do airline pilots actually earn? First officer and captain salaries explained.", href: "/guides/airline-pilot-salary", time: "7 min read", category: "Career", emoji: "📈" },
  { title: "The UK Pilot Shortage 2026", description: "Is the shortage real? What it means for your hiring prospects, salary, and career timeline.", href: "/guides/uk-pilot-shortage-2026", time: "7 min read", category: "Career", emoji: "📊" },
  { title: "UK Pilot Salary Guide 2026", description: "Real salary figures for first officers and captains at every major UK airline.", href: "/guides/uk-pilot-salary-2026", time: "8 min read", category: "Career", emoji: "💷" },
  { title: "Airline Pilot Interview Guide", description: "What happens in airline selection, what assessors look for, and how to prepare properly.", href: "/guides/airline-pilot-interview", time: "9 min read", category: "Career", emoji: "🎯" },
  { title: "Women in Aviation UK", description: "Scholarships, challenges, industry progress and support organisations for women pursuing a pilot career.", href: "/guides/women-in-aviation-uk", time: "7 min read", category: "Career", emoji: "✈️" },
  { title: "Pilot CV & Cover Letter Guide", description: "How to write a pilot CV and cover letter that gets you to interview — structure, content, and what to avoid.", href: "/guides/pilot-cv-cover-letter", time: "8 min read", category: "Career", emoji: "📄" },
  { title: "Airline Simulator Assessment Guide", description: "What to expect in the sim assessment, how it's scored, and how to prepare for raw flying and CRM.", href: "/guides/airline-simulator-assessment", time: "8 min read", category: "Career", emoji: "🕹️" },
  { title: "How to Become a First Officer at a UK Airline", description: "Minimum requirements, type rating costs, FO salary, and which airlines hire low-hours pilots.", href: "/guides/first-officer-uk", time: "9 min read", category: "Career", emoji: "🪑" },

  // ── Cadet Programmes ─────────────────────────────────────────────────────────
  { title: "Cadet Pilot Programmes UK", description: "Every sponsored cadet scheme in the UK — BA, Jet2, Ryanair, easyJet — eligibility and how to apply.", href: "/guides/cadet-pilot-programmes-uk", time: "8 min read", category: "Cadet Programmes", emoji: "🎓" },
  { title: "BA Speedbird Academy 2026", description: "Complete guide to BA's flagship cadet programme — selection, training at CAE Oxford, costs, and guaranteed FO job.", href: "/guides/ba-speedbird-academy", time: "10 min read", category: "Cadet Programmes", emoji: "✈️" },
  { title: "easyJet Generation Pilot 2026", description: "The MPL route from zero hours to easyJet First Officer — how it works, costs, and how to get in.", href: "/guides/easyjet-generation-pilot", time: "9 min read", category: "Cadet Programmes", emoji: "🟠" },
  { title: "Ryanair Cadet Programme 2026", description: "How Ryanair recruits cadets via FTEJerez, Bartolini Air, and MATS — costs from £47k, selection, and career.", href: "/guides/ryanair-cadet-programme", time: "8 min read", category: "Cadet Programmes", emoji: "🔵" },
  { title: "Wizz Air Pilot Academy 2026", description: "Europe's fastest-growing airline's cadet programme — training, costs, and what a Wizz Air career looks like.", href: "/guides/wizz-air-pilot-academy", time: "8 min read", category: "Cadet Programmes", emoji: "🟣" },
  { title: "TUI Airways MPL Programme 2026", description: "TUI's MPL cadet pathway from zero hours to Boeing 737 FO — selection, training, costs, and career.", href: "/guides/tui-mpl-cadet-programme", time: "8 min read", category: "Cadet Programmes", emoji: "🌴" },
],
  },
  'us': {
    label: 'United States',
    flag: '🇺🇸',
    regulator: 'FAA',
    roadmapHref: '/us/roadmap',
    cadetToolHref: '/us/cadet-eligibility',
    medicalToolHref: '/us/medical-lookup',
    calculatorHref: '/us/calculator',
    isThin: false,
    guides: [
  // Getting Started
  {
    title: "How to Become a Pilot in the USA",
    description: "The complete 2026 guide to FAA licences, Part 141 vs Part 61, ATP minimums, airline cadet programmes, and the R-ATP 1,000-hour advantage.",
    href: "/us/guides/how-to-become-a-pilot",
    time: "9 min read",
    category: "Getting Started",
    emoji: "🛫",
  },
  {
    title: "Part 61 vs Part 141: Which is Right for You?",
    description: "The honest comparison of the two FAA training structures — minimum hours, cost differences, school types, and which route fits your situation.",
    href: "/us/guides/part-61-vs-141",
    time: "8 min read",
    category: "Getting Started",
    emoji: "⚖️",
  },
  {
    title: "PPL Requirements USA (2026)",
    description: "Everything you need to know about getting your FAA Private Pilot Licence — minimum hours, written test, checkride, costs, and how long it takes.",
    href: "/us/guides/ppl-requirements-usa",
    time: "7 min read",
    category: "Getting Started",
    emoji: "🪂",
  },
  {
    title: "Commercial Pilot Certificate USA",
    description: "How to earn your FAA Commercial Pilot Certificate — hour requirements, knowledge test, practical test standards, and what jobs it unlocks.",
    href: "/us/guides/commercial-pilot-certificate-usa",
    time: "8 min read",
    category: "Getting Started",
    emoji: "🏆",
  },
  {
    title: "ATP Certificate USA: The Final Step to the Airlines",
    description: "The Airline Transport Pilot certificate explained — R-ATP vs full ATP, hour requirements, knowledge test, and how to get hired at a regional airline.",
    href: "/us/guides/atp-certificate-usa",
    time: "8 min read",
    category: "Getting Started",
    emoji: "✈️",
  },
  // Career & Salary
  {
    title: "US Airline Pilot Salary (2026)",
    description: "Regional vs major airline pay, First Officer vs Captain earnings, per diem, and how long it takes to reach the six-figure salary at United, Delta, and American.",
    href: "/us/guides/airline-pilot-salary-usa",
    time: "7 min read",
    category: "Career & Salary",
    emoji: "💰",
  },
  {
    title: "US Pilot Career Outlook 2026",
    description: "Is the pilot shortage real? Hiring trends at regional and major airlines, mandatory retirement age, and what the next 10 years look like for new pilots.",
    href: "/us/guides/us-pilot-career-outlook",
    time: "7 min read",
    category: "Career & Salary",
    emoji: "📈",
  },
  {
    title: "CFI Career USA: Become a Flight Instructor",
    description: "How to become a Certified Flight Instructor — CFI, CFII, MEI ratings, pay rates, hour-building strategy, and using instructing as a pathway to the airlines.",
    href: "/us/guides/cfi-career-usa",
    time: "7 min read",
    category: "Career & Salary",
    emoji: "🎓",
  },
  // Finance & Funding
  {
    title: "How to Fund Pilot Training in the USA",
    description: "Sallie Mae flight school loans, AOPA finance, VA benefits, scholarships, and the Part 141 federal student aid advantage — every funding option explained.",
    href: "/us/guides/how-to-fund-pilot-training-usa",
    time: "8 min read",
    category: "Finance & Funding",
    emoji: "🏦",
  },
  {
    title: "GI Bill Flight Training: The Complete Guide",
    description: "How veterans can use the Post-9/11 GI Bill and Montgomery GI Bill for FAA pilot training — eligible programmes, approved schools, and how to apply.",
    href: "/us/guides/gi-bill-flight-training",
    time: "8 min read",
    category: "Finance & Funding",
    emoji: "🎖️",
  },
  // Medical
  {
    title: "FAA Medical Requirements (2026)",
    description: "First, Second, and Third Class medical standards — what the AME checks, common disqualifiers, Special Issuance, and how to prepare for your exam.",
    href: "/us/guides/faa-medical-requirements",
    time: "7 min read",
    category: "Medical",
    emoji: "🏥",
  },
  {
    title: "ADHD and FAA Medical: What You Need to Know",
    description: "Can you get an FAA medical with ADHD? The Special Issuance process, approved medications, neuropsychological testing requirements, and real approval timelines.",
    href: "/us/guides/adhd-faa-medical",
    time: "7 min read",
    category: "Medical",
    emoji: "🧠",
  },
  // Ratings
  {
    title: "Instrument Rating USA: Complete Guide",
    description: "FAA Instrument Rating requirements, training structure, written test, checkride, and why it's the most important rating you'll earn after your PPL.",
    href: "/us/guides/instrument-rating-usa",
    time: "7 min read",
    category: "Ratings",
    emoji: "🌫️",
  },
  {
    title: "Type Ratings in the USA: Costs, Process & 2026 Guide",
    description: "How airline type ratings work in the US, who pays, costs ($20,000–$35,000 self-funded), and which airlines provide type rating training as part of hiring.",
    href: "/us/guides/type-rating-usa",
    time: "8 min read",
    category: "Ratings",
    emoji: "🛩️",
  },
  // Flight Schools
  {
    title: "Best Flight Schools in the USA 2026",
    description: "ATP Flight School, United Aviate Academy, Embry-Riddle, L3Harris, CAE, Epic — compare costs, airline partnerships, and completion rates.",
    href: "/us/guides/best-flight-schools-usa",
    time: "11 min read",
    category: "Flight Schools",
    emoji: "🏫",
  },
  {
    title: "ATP Flight School 2026: Complete Review",
    description: "America's largest flight school — Airline Career Pilot Program ($123,995), airline partner guarantees, CFI pathway, financing, and honest pros/cons.",
    href: "/us/guides/atp-flight-school-guide",
    time: "11 min read",
    category: "Flight Schools",
    emoji: "🏆",
  },
  {
    title: "Embry-Riddle Aeronautical University: Pilot Programme Guide 2026",
    description: "Is ERAU worth the $220,000+ cost? Airline partnerships, R-ATP eligibility, Daytona vs Prescott, graduate outcomes, and an honest cost-benefit analysis.",
    href: "/us/guides/embry-riddle-aeronautical-university",
    time: "13 min read",
    category: "Flight Schools",
    emoji: "🎓",
  },
  // Airline Cadet Programmes
  {
    title: "United Aviate Academy 2026: Complete Guide",
    description: "Everything about United Airlines' cadet programme — eligibility, costs ($111,700–$122,000), application process, Aviate ID, and how to maximise your chances.",
    href: "/us/guides/united-aviate-program",
    time: "12 min read",
    category: "Airline Cadet Programmes",
    emoji: "🔵",
  },
  {
    title: "Delta Propel Program 2026: Complete Guide",
    description: "Delta Air Lines' cadet programme — partner schools, Propel ID system, eligibility, timeline to Delta FO, and how it compares to United Aviate.",
    href: "/us/guides/delta-propel-program",
    time: "10 min read",
    category: "Airline Cadet Programmes",
    emoji: "🔴",
  },
  // Career Preparation
  {
    title: "US Airline Pilot Interview Guide 2026",
    description: "How to prepare for US airline assessments — TBAS/ASTB tests, simulator sessions, HR interviews, CRM evaluations. United, Delta, American, Southwest, and regionals.",
    href: "/us/guides/airline-interview-usa",
    time: "11 min read",
    category: "Career Preparation",
    emoji: "🎤",
  },
  {
    title: "US Pilot Aptitude Tests 2026: TBAS, ASTB & Airline Assessments",
    description: "Complete guide to TBAS, ASTB-E, and airline-specific aptitude tests. How to prepare, what to expect, and how to score in the top percentile.",
    href: "/us/guides/pilot-aptitude-test-usa",
    time: "8 min read",
    category: "Career Preparation",
    emoji: "🧪",
  },
  {
    title: "Airline Pilot Resume & Cover Letter Guide USA 2026",
    description: "How to write a US airline pilot resume — logbook summary, certificates, hours breakdown, and cover letter tips for United, Delta, American, Southwest.",
    href: "/us/guides/pilot-resume-usa",
    time: "8 min read",
    category: "Career Preparation",
    emoji: "📄",
  },
  {
    title: "Military Pilot to Airline: The Complete US Transition Guide 2026",
    description: "How US military pilots transition to airline careers — JTIP programme, military experience credit toward ATP, which airlines recruit military pilots, and timeline.",
    href: "/us/guides/military-to-airline-usa",
    time: "10 min read",
    category: "Career Preparation",
    emoji: "🎖️",
  },
  // Hour Building
  {
    title: "How to Build Flight Hours in the USA: Complete 2026 Guide",
    description: "CFI route, banner towing, pipeline patrol, skydive pilot, charter flying — all methods for building hours from CPL to ATP minimums, with costs and timelines.",
    href: "/us/guides/hour-building-usa",
    time: "9 min read",
    category: "Hour Building",
    emoji: "⏱️",
  },
  {
    title: "US Pilot Training Timeline: Zero to Airline in 2026",
    description: "Realistic step-by-step timeline from zero hours to regional airline First Officer — PPL, IR, CPL, CFI, hour building, ATP written, regional hiring. Total: 3–4 years.",
    href: "/us/guides/pilot-training-timeline-usa",
    time: "9 min read",
    category: "Hour Building",
    emoji: "📅",
  },
  // Finance
  {
    title: "How Much Does Pilot Training Cost in the USA? 2026",
    description: "Full breakdown of all US pilot training costs — PPL ($10–15k), IR, CPL, CFI, total zero-to-ATP ($100–130k). Part 61 vs 141 vs Embry-Riddle vs ATP Flight School.",
    href: "/us/guides/pilot-training-costs-usa",
    time: "10 min read",
    category: "Finance & Funding",
    emoji: "💵",
  },
  // Diversity & Inclusion
  {
    title: "Women in Aviation USA: Scholarships, Programmes & Career Guide 2026",
    description: "WAI, Ninety-Nines, airline diversity programmes, key scholarships, current statistics (women are ~7% of US airline pilots), and how to break in.",
    href: "/us/guides/women-in-aviation-usa",
    time: "9 min read",
    category: "Diversity & Inclusion",
    emoji: "👩‍✈️",
  },
  // Career Changers
  {
    title: "Am I Too Old to Become a Pilot in the USA? 2026",
    description: "FAA age rules (no upper limit for PPL/CPL, mandatory retirement at 65), realistic timelines for career changers aged 30–50, and real examples of late starters.",
    href: "/us/guides/am-i-too-old-to-become-a-pilot-usa",
    time: "8 min read",
    category: "Career Changers",
    emoji: "🕐",
  },
  {
    title: "Becoming a Pilot Over 40 in the USA: Complete 2026 Guide",
    description: "Realistic guide for career changers over 40 — FAA medical considerations, timeline to ATP, regional vs major airline prospects, financing, and what's achievable.",
    href: "/us/guides/pilot-training-over-40-usa",
    time: "9 min read",
    category: "Career Changers",
    emoji: "🔄",
  },
  {
    title: "The US Pilot Shortage 2026: What It Means for Your Career",
    description: "Boeing projects 17,000 new pilots needed per year through 2042. Regional airline hiring surge, upgrade timelines, starting salaries, and why now is the best time to start.",
    href: "/us/guides/us-pilot-shortage-2026",
    time: "8 min read",
    category: "Career & Salary",
    emoji: "📊",
  },
  {
    title: "US Airline Pilot Salary 2026: Real Pay Scales",
    description: "Real 2026 pay scales from Delta, United, American, Southwest, and regional carriers. Per diem, profit-sharing, and full career earnings breakdown.",
    href: "/us/guides/us-pilot-salary-2026",
    time: "12 min read",
    category: "Career & Salary",
    emoji: "💵",
  },
  {
    title: "US Regional Airlines Guide 2026",
    description: "How regional airlines work as the gateway to major carriers. Hiring requirements, upgrade timelines, and which regionals have the best flow-through agreements.",
    href: "/us/guides/us-regional-airlines-guide",
    time: "10 min read",
    category: "Career & Salary",
    emoji: "🛫",
  },
  {
    title: "US Military Pilot to Airlines 2026",
    description: "Transitioning from US military to commercial aviation. R-ATP at 750 hours, MilComp credits, ATP CTP waiver, and which airlines prioritise military hires.",
    href: "/us/guides/us-military-pilot-to-airlines",
    time: "10 min read",
    category: "Career & Salary",
    emoji: "🪖",
  },
  {
    title: "US Airline Pilot Benefits 2026",
    description: "Beyond the hourly rate: 16-18% direct 401(k) contributions, profit sharing, loss of license insurance, and non-revenue travel explained.",
    href: "/us/guides/us-pilot-benefits",
    time: "11 min read",
    category: "Career & Salary",
    emoji: "🏦",
  },
  {
    title: "US Airline Pilot Retirement Age 2026",
    description: "The FAA mandates retirement at 65 for Part 121 airline pilots. How the rule works, the push to raise it to 67, and what it means for your career timeline.",
    href: "/us/guides/us-pilot-retirement-age",
    time: "8 min read",
    category: "Career & Salary",
    emoji: "📅",
  },
  {
    title: "US Pilot Taxes 2026: Deductions & Planning",
    description: "Tax deductions available to US airline pilots: per diem, uniform costs, union dues, training expenses, and how to use a 529 plan for flight training.",
    href: "/us/guides/us-pilot-taxes",
    time: "9 min read",
    category: "Career & Salary",
    emoji: "🧾",
  },
  {
    title: "US Pilot Housing 2026: Crash Pads & Living",
    description: "Where US airline pilots live and how crash pads work. Cost comparison of living in base vs commuting, and the best cities for pilot quality of life.",
    href: "/us/guides/us-pilot-housing",
    time: "8 min read",
    category: "Career & Salary",
    emoji: "🏠",
  },
  // Medical — detailed class guides
  {
    title: "FAA First Class Medical: Full Requirements 2026",
    description: "Everything required for an FAA First Class Medical Certificate — vision, hearing, cardiovascular, mental health, and how to prepare for your AME exam.",
    href: "/us/guides/faa-medical-class-1",
    time: "8 min read",
    category: "Medical",
    emoji: "🏥",
  },
  {
    title: "FAA Second Class Medical: Requirements & Differences 2026",
    description: "How the FAA Second Class Medical differs from First Class, who needs it, and what commercial pilots must maintain to keep their certificate current.",
    href: "/us/guides/faa-medical-class-2",
    time: "7 min read",
    category: "Medical",
    emoji: "🩺",
  },
  {
    title: "FAA Third Class Medical: Private Pilot Requirements 2026",
    description: "The FAA Third Class Medical explained — BasicMed as an alternative, eligibility, duration, and what conditions are most commonly flagged.",
    href: "/us/guides/faa-medical-class-3",
    time: "7 min read",
    category: "Medical",
    emoji: "📋",
  },
  // Ratings — ATP requirements
  {
    title: "FAA ATP Requirements 2026: The Complete Guide",
    description: "Full breakdown of FAA ATP certificate requirements — 1,500 hours (or R-ATP), ATP CTP, knowledge test, and the practical test standards.",
    href: "/us/guides/faa-atp-requirements",
    time: "8 min read",
    category: "Ratings",
    emoji: "📜",
  },
  // Career Preparation
  {
    title: "US Airline Interview Preparation 2026",
    description: "How to prepare for major and regional airline interviews — HR questions, technical oral, sim evaluation, and what Delta, United, American, and Southwest look for.",
    href: "/us/guides/airline-interview-prep",
    time: "10 min read",
    category: "Career Preparation",
    emoji: "🎯",
  },
  {
    title: "Major US Airlines Hiring 2026: Who Is Recruiting?",
    description: "Current hiring status at Delta, United, American, Southwest, Alaska, and JetBlue — minimums, flow-through agreements, and how to get your application noticed.",
    href: "/us/guides/major-airlines-hiring-usa",
    time: "9 min read",
    category: "Career Preparation",
    emoji: "📊",
  },
  {
    title: "US Airline Cadet Programs 2026: Complete Guide",
    description: "Every major US airline cadet pathway compared — United Aviate, Delta Propel, American Cadet Academy, Southwest Destination 225°. Eligibility, costs, and timelines.",
    href: "/us/guides/us-cadet-programs",
    time: "11 min read",
    category: "Airline Cadet Programmes",
    emoji: "🔗",
  },
  // Finance
  {
    title: "US Flight School Loans 2026: Sallie Mae, AOPA & More",
    description: "Every loan option for US pilot training — Sallie Mae, AOPA, Stratus Financial, Climb Credit, and VA benefits. Rates, terms, and how to choose.",
    href: "/us/guides/us-flight-school-loans",
    time: "8 min read",
    category: "Finance & Funding",
    emoji: "💳",
  },
  // Pilot Lifestyle
  {
    title: "US Pilot Schedule 2026: Rosters, Days Off & Work-Life Balance",
    description: "How US airline pilot schedules work — bidding systems, reserve, line holder, days off per month, and how lifestyle differs by airline and fleet type.",
    href: "/us/guides/us-pilot-schedule",
    time: "8 min read",
    category: "Career & Salary",
    emoji: "🗓️",
  },
  {
    title: "US Airline Pilot Commuting 2026: Is It Worth It?",
    description: "How commuting works for US airline pilots — non-rev travel, crash pads, commuter clauses, and whether living away from base makes financial sense.",
    href: "/us/guides/us-pilot-commuting",
    time: "8 min read",
    category: "Career & Salary",
    emoji: "🛫",
  },
  {
    title: "US Airline Pilot Seniority 2026: How It Works",
    description: "The seniority system explained — how it affects pay, schedule, base, aircraft type, and upgrade timeline at US airlines. Why seniority is everything.",
    href: "/us/guides/us-pilot-seniority",
    time: "8 min read",
    category: "Career & Salary",
    emoji: "📊",
  },
  // Overview guides
  {
    title: "US Pilot Training 2026: The Complete Overview",
    description: "The definitive 2026 overview of becoming a pilot in the United States — FAA licences, costs, timelines, airline pathways, and the current hiring market.",
    href: "/us/guides/us-pilot-training-2026",
    time: "12 min read",
    category: "Getting Started",
    emoji: "🇺🇸",
  },
  {
    title: "US Pilot Training Market Guide 2026",
    description: "A data-driven look at the US pilot training market — school costs, airline demand, regional vs major pathways, and how to position yourself for success.",
    href: "/us/guides/us-pilot-training-market-guide",
    time: "10 min read",
    category: "Getting Started",
    emoji: "📊",
  },
],
  },
  'australia': {
    label: 'Australia',
    flag: '🇦🇺',
    regulator: 'CASA',
    roadmapHref: '/roadmap',
    cadetToolHref: '/tools/cadet-eligibility',
    medicalToolHref: '/tools/class-1-medical-check',
    calculatorHref: '/calculator',
    isThin: false,
    guides: [
  // Getting Started
  { title: "How to Become a Pilot in Australia", description: "The complete 2026 guide to CASA licences, Part 141 vs 142, costs (AUD $65k–$120k), and the Qantas Academy pathway.", href: "/guides/how-to-become-a-pilot-australia", time: "12 min read", category: "Getting Started", emoji: "🛫" },
  { title: "Australia Pilot Shortage 2026", description: "Is the Australian pilot shortage real? What it means for hiring timelines, salary, and your career prospects.", href: "/australia/guides/australia-pilot-shortage", time: "7 min read", category: "Getting Started", emoji: "📊" },
  { title: "Pilot Seniority in Australia", description: "How seniority works at Australian airlines — what it controls, how to build it, and why it matters.", href: "/australia/guides/pilot-seniority", time: "7 min read", category: "Getting Started", emoji: "📈" },

  // Training Routes
  { title: "CASA ATPL Requirements", description: "Full breakdown of CASA ATPL certificate requirements — hours, ratings, knowledge tests, and checkrides.", href: "/australia/guides/casa-atpl-requirements", time: "8 min read", category: "Training Routes", emoji: "📋" },
  { title: "CASA CPL Requirements", description: "CASA CPL requirements, what jobs it unlocks, and how it fits into the airline career pathway.", href: "/australia/guides/casa-cpl-requirements", time: "7 min read", category: "Training Routes", emoji: "📋" },
  { title: "Best Flight Schools Australia 2026", description: "Data-driven comparison of Australia's top flight schools — outcomes, costs, fleet, and student reviews.", href: "/australia/guides/best-flight-schools-australia", time: "10 min read", category: "Training Routes", emoji: "🏫" },
  { title: "How to Become a Flight Instructor in Australia", description: "FI rating requirements, salary, and how instructing fits into the Australian hour-building strategy.", href: "/australia/guides/australia-flight-instructor", time: "8 min read", category: "Training Routes", emoji: "👨‍🏫" },

  // Medical
  { title: "CASA Class 1 Medical", description: "CASA Class 1 medical requirements, what the DAME examines, common disqualifiers, and how to prepare.", href: "/australia/guides/casa-medical-class-1", time: "7 min read", category: "Medical", emoji: "🩺" },

  // Costs & Finance
  { title: "Australia Pilot Training Costs 2026", description: "Real cost breakdown for Australian pilot training — CASA PPL to ATPL, hour building, and type ratings.", href: "/australia/guides/australia-pilot-training-costs", time: "9 min read", category: "Costs & Finance", emoji: "💰" },
  { title: "Australia Flight School Loans", description: "Every loan and funding option for Australian pilot training — VET Student Loans, bank finance, and scholarships.", href: "/australia/guides/australia-flight-school-loans", time: "8 min read", category: "Costs & Finance", emoji: "💳" },

  // Career
  { title: "Australia Pilot Salary 2026", description: "Real salary figures for Australian first officers and captains at Qantas, Virgin, Rex, and regional carriers.", href: "/australia/guides/australia-pilot-salary-2026", time: "9 min read", category: "Career", emoji: "💵" },
  { title: "Australia Pilot Benefits", description: "What Australian airline pilots get beyond base salary — travel perks, super, rostering, and allowances.", href: "/australia/guides/australia-pilot-benefits", time: "6 min read", category: "Career", emoji: "🎁" },
  { title: "Australia Pilot Schedule", description: "What an Australian airline pilot's roster actually looks like — reserve, line, and quality of life.", href: "/australia/guides/australia-pilot-schedule", time: "7 min read", category: "Career", emoji: "📅" },
  { title: "Australia Pilot Commuting", description: "How commuting works at Australian airlines — interstate basing, crash pads, and the real cost.", href: "/australia/guides/australia-pilot-commuting", time: "7 min read", category: "Career", emoji: "🚆" },
  { title: "Australia Pilot Bases", description: "Where Australian airlines are based, which cities have the most flying, and how base preferences work.", href: "/australia/guides/australia-pilot-bases", time: "6 min read", category: "Career", emoji: "📍" },
  { title: "Australia Pilot Taxes", description: "How Australian pilot income is taxed — allowances, deductions, and what to claim.", href: "/australia/guides/australia-pilot-taxes", time: "6 min read", category: "Career", emoji: "🧾" },
  { title: "Australia Regional Airlines Guide", description: "Regional airline careers in Australia — Rex, Bonza, Alliance, and the pathway to the majors.", href: "/australia/guides/australia-regional-airlines", time: "7 min read", category: "Career", emoji: "🗺️" },
  { title: "Military to Airlines in Australia", description: "How Australian military pilots transition to civilian airlines — RAAF pathways, credits, and timelines.", href: "/australia/guides/australia-military-to-airlines", time: "8 min read", category: "Career", emoji: "🪖" },

  // Cadet Programmes
  { title: "Qantas Group Pilot Academy", description: "Complete guide to the Qantas Group Pilot Academy — selection, training, costs, and the guaranteed FO pathway.", href: "/australia/guides/qantas-group-pilot-academy", time: "10 min read", category: "Cadet Programmes", emoji: "🦘" },
  { title: "Rex Pilot Academy", description: "Rex Airlines' cadet programme — how it works, costs, selection, and the regional-to-mainline pathway.", href: "/australia/guides/rex-pilot-academy", time: "8 min read", category: "Cadet Programmes", emoji: "🔴" },
  { title: "Virgin Australia Cadet Pilot Program", description: "Virgin Australia's cadet pathway — selection criteria, training structure, and career prospects.", href: "/australia/guides/virgin-australia-cadet-pilot-program", time: "8 min read", category: "Cadet Programmes", emoji: "🟣" },
],
  },
  'canada': {
    label: 'Canada',
    flag: '🇨🇦',
    regulator: 'Transport Canada',
    roadmapHref: '/roadmap',
    cadetToolHref: '/tools/cadet-eligibility',
    medicalToolHref: '/tools/class-1-medical-check',
    calculatorHref: '/calculator',
    isThin: false,
    guides: [
  // Getting Started
  { title: "How to Become a Pilot in Canada", description: "Transport Canada PPL to ATPL, real costs (CAD $80k–$130k), hour building in northern Canada, and aviation college pathways.", href: "/guides/how-to-become-a-pilot-canada", time: "11 min read", category: "Getting Started", emoji: "🛫" },
  { title: "Canada Pilot Shortage 2026", description: "The real state of the Canadian pilot shortage — data, causes, and what it means for your career timeline.", href: "/canada/guides/canada-pilot-shortage", time: "7 min read", category: "Getting Started", emoji: "📊" },

  // Training Routes
  { title: "Transport Canada ATPL Requirements", description: "Full breakdown of TC ATPL requirements — hours, ratings, knowledge tests, and checkrides.", href: "/canada/guides/tc-atpl-requirements", time: "8 min read", category: "Training Routes", emoji: "📋" },
  { title: "Transport Canada CPL Requirements", description: "TC CPL requirements, what jobs it unlocks, and how it fits into the airline career pathway.", href: "/canada/guides/transport-canada-cpl-requirements", time: "7 min read", category: "Training Routes", emoji: "📋" },
  { title: "Best Flight Schools Canada 2026", description: "Data-driven comparison of Canada's top flight schools — outcomes, costs, fleet, and student reviews.", href: "/canada/guides/best-flight-schools-canada", time: "10 min read", category: "Training Routes", emoji: "🏫" },
  { title: "How to Become a Flight Instructor in Canada", description: "FI rating requirements, salary, and how instructing fits into the Canadian hour-building strategy.", href: "/canada/guides/canada-flight-instructor", time: "8 min read", category: "Training Routes", emoji: "👨‍🏫" },

  // Medical
  { title: "Transport Canada Class 1 Medical", description: "TC Class 1 medical requirements, what the CAME examines, common disqualifiers, and how to prepare.", href: "/canada/guides/tc-medical-class-1", time: "7 min read", category: "Medical", emoji: "🩺" },

  // Costs & Finance
  { title: "Canada Pilot Training Costs 2026", description: "Real cost breakdown for Canadian pilot training — TC PPL to ATPL, hour building, and type ratings.", href: "/canada/guides/canada-pilot-training-costs", time: "9 min read", category: "Costs & Finance", emoji: "💰" },
  { title: "Canada Flight School Loans", description: "Every loan and funding option for Canadian pilot training — OSAP, bank finance, and scholarships.", href: "/canada/guides/canada-flight-school-loans", time: "8 min read", category: "Costs & Finance", emoji: "💳" },

  // Career
  { title: "Canada Pilot Salary 2026", description: "Real salary figures for Canadian first officers and captains at Air Canada, WestJet, Jazz, and regional carriers.", href: "/canada/guides/canada-pilot-salary-2026", time: "9 min read", category: "Career", emoji: "💵" },
  { title: "Canada Pilot Benefits", description: "What Canadian airline pilots get beyond base salary — travel perks, pension, rostering, and allowances.", href: "/canada/guides/canada-pilot-benefits", time: "6 min read", category: "Career", emoji: "🎁" },
  { title: "Canada Pilot Schedule", description: "What a Canadian airline pilot's roster actually looks like — reserve, line, and quality of life.", href: "/canada/guides/canada-pilot-schedule", time: "7 min read", category: "Career", emoji: "📅" },
  { title: "Canada Pilot Commuting", description: "How commuting works at Canadian airlines — cross-country basing, crash pads, and the real cost.", href: "/canada/guides/canada-pilot-commuting", time: "7 min read", category: "Career", emoji: "🚆" },
  { title: "Canada Pilot Bases", description: "Where Canadian airlines are based, which cities have the most flying, and how base preferences work.", href: "/canada/guides/canada-pilot-bases", time: "6 min read", category: "Career", emoji: "📍" },
  { title: "Canada Pilot Taxes", description: "How Canadian pilot income is taxed — allowances, deductions, and what to claim.", href: "/canada/guides/canada-pilot-taxes", time: "6 min read", category: "Career", emoji: "🧾" },
  { title: "Canada Pilot Seniority Guide", description: "How seniority works at Canadian airlines — what it controls, how to build it, and why it matters.", href: "/canada/guides/canada-pilot-seniority", time: "7 min read", category: "Career", emoji: "📈" },
  { title: "Canada Regional Airlines Guide", description: "Regional airline careers in Canada — Jazz, PAL, Central Mountain Air, and the pathway to the majors.", href: "/canada/guides/canada-regional-airlines", time: "7 min read", category: "Career", emoji: "🗺️" },
  { title: "Military to Airlines in Canada", description: "How Canadian military pilots transition to civilian airlines — RCAF pathways, credits, and timelines.", href: "/canada/guides/canada-military-to-airlines", time: "8 min read", category: "Career", emoji: "🪖" },

  // Cadet Programmes
  { title: "Air Canada Jazz Cadet Program", description: "Jazz Aviation's cadet pathway — how it works, selection, training, and the Air Canada Express career track.", href: "/canada/guides/air-canada-jazz-cadet", time: "9 min read", category: "Cadet Programmes", emoji: "🍁" },
  { title: "WestJet Encore Cadet Program", description: "WestJet Encore's cadet programme — selection criteria, training structure, and career prospects.", href: "/canada/guides/westjet-encore-cadet", time: "8 min read", category: "Cadet Programmes", emoji: "🔵" },
  { title: "Porter Airlines Cadet Program", description: "Porter Airlines' cadet pathway — how it works, costs, selection, and the regional-to-mainline pathway.", href: "/canada/guides/porter-airlines-cadet-program", time: "8 min read", category: "Cadet Programmes", emoji: "🟤" },
  { title: "Canada Cadet Programs 2026", description: "Every Canadian airline cadet and pathway program — eligibility, costs, and how to apply.", href: "/canada/guides/canada-cadet-programs", time: "9 min read", category: "Cadet Programmes", emoji: "🎓" },
],
  },
  'europe': {
    label: 'Europe',
    flag: '🇪🇺',
    regulator: 'EASA',
    roadmapHref: '/roadmap',
    cadetToolHref: '/tools/cadet-eligibility',
    medicalToolHref: '/tools/class-1-medical-check',
    calculatorHref: '/calculator',
    isThin: true,
    guides: [
  // Getting Started
  { title: "How to Become a Pilot in Europe (EASA)", description: "EASA integrated vs modular ATPL, costs across 15 countries (€40k–€130k), and Lufthansa, Wizz Air, and Ryanair cadet programmes.", href: "/guides/how-to-become-a-pilot-europe", time: "13 min read", category: "Getting Started", emoji: "🛫" },
  { title: "Europe Pilot Shortage 2026", description: "The real state of the European pilot shortage — data, causes, and what it means for your career timeline.", href: "/europe/guides/europe-pilot-shortage", time: "7 min read", category: "Getting Started", emoji: "📊" },

  // Training Routes
  { title: "EASA ATPL Requirements", description: "Full breakdown of EASA ATPL requirements — hours, ratings, theory exams, and checkrides.", href: "/europe/guides/easa-atpl-requirements", time: "8 min read", category: "Training Routes", emoji: "📋" },
  { title: "EASA CPL Requirements", description: "EASA CPL requirements, what jobs it unlocks, and how it fits into the airline career pathway.", href: "/europe/guides/easa-cpl-requirements", time: "7 min read", category: "Training Routes", emoji: "📋" },
  { title: "Best Flight Schools Europe 2026", description: "Data-driven comparison of Europe's top flight schools — outcomes, costs, fleet, and student reviews.", href: "/europe/guides/best-flight-schools-europe", time: "10 min read", category: "Training Routes", emoji: "🏫" },
  { title: "How to Become a Flight Instructor in Europe", description: "EASA FI rating requirements, salary, and how instructing fits into the European hour-building strategy.", href: "/europe/guides/europe-flight-instructor", time: "8 min read", category: "Training Routes", emoji: "👨‍🏫" },
  { title: "Military to Airlines in Europe", description: "How European military pilots transition to civilian airlines — pathways, licence conversions, and timelines.", href: "/europe/guides/military-to-airlines", time: "8 min read", category: "Training Routes", emoji: "🪖" },

  // Medical
  { title: "EASA Class 1 Medical", description: "EASA Class 1 medical requirements, what the AME examines, common disqualifiers, and how to prepare.", href: "/europe/guides/easa-medical-class-1", time: "7 min read", category: "Medical", emoji: "🩺" },

  // Costs & Finance
  { title: "Europe Pilot Training Costs 2026", description: "Real cost breakdown for European pilot training — EASA PPL to ATPL across different countries.", href: "/europe/guides/pilot-training-costs", time: "9 min read", category: "Costs & Finance", emoji: "💰" },
  { title: "Europe Flight School Loans", description: "Every loan and funding option for European pilot training — country-specific schemes, bank finance, and scholarships.", href: "/europe/guides/europe-flight-school-loans", time: "8 min read", category: "Costs & Finance", emoji: "💳" },

  // Career
  { title: "Europe Pilot Salary 2026", description: "Real salary figures for European first officers and captains at Ryanair, Wizz Air, Lufthansa, and other carriers.", href: "/europe/guides/pilot-salary-2026", time: "9 min read", category: "Career", emoji: "💶" },
  { title: "Europe Pilot Seniority Guide", description: "How seniority works at European airlines — what it controls, how to build it, and why it matters.", href: "/europe/guides/europe-pilot-seniority", time: "7 min read", category: "Career", emoji: "📈" },
  { title: "Europe Regional Airlines Guide", description: "Regional airline careers in Europe — the pathway from regional to mainline carriers.", href: "/europe/guides/europe-regional-airlines-pilot-training", time: "7 min read", category: "Career", emoji: "🗺️" },

  // Cadet Programmes
  { title: "Lufthansa European Flight Academy", description: "Complete guide to Lufthansa's cadet programme — selection, training, costs, and the guaranteed FO pathway.", href: "/europe/guides/lufthansa-european-flight-academy", time: "10 min read", category: "Cadet Programmes", emoji: "🟡" },
  { title: "Air France-KLM Cadet Pilot Program", description: "Air France-KLM's cadet pathway — how it works, selection, training, and career prospects.", href: "/europe/guides/air-france-klm-cadet-pilot-program", time: "9 min read", category: "Cadet Programmes", emoji: "🔵" },
  { title: "Europe Cadet Programs 2026", description: "Every major European airline cadet and pathway program — eligibility, costs, and how to apply.", href: "/europe/guides/europe-cadet-programs", time: "9 min read", category: "Cadet Programmes", emoji: "🎓" },
],
  },
  'new-zealand': {
    label: 'New Zealand',
    flag: '🇳🇿',
    regulator: 'CAA NZ',
    roadmapHref: '/roadmap',
    cadetToolHref: '/tools/cadet-eligibility',
    medicalToolHref: '/tools/class-1-medical-check',
    calculatorHref: '/calculator',
    isThin: true,
    guides: [
  // Getting Started
  { title: "New Zealand Pilot Shortage 2026", description: "The real state of the New Zealand pilot shortage — data, causes, and what it means for your career timeline.", href: "/new-zealand/guides/new-zealand-pilot-shortage", time: "7 min read", category: "Getting Started", emoji: "📊" },

  // Training Routes
  { title: "NZ ATPL Requirements", description: "Full breakdown of CAA New Zealand ATPL requirements — hours, ratings, knowledge tests, and checkrides.", href: "/new-zealand/guides/nz-atpl-requirements", time: "8 min read", category: "Training Routes", emoji: "📋" },
  { title: "NZ CPL Requirements", description: "New Zealand CPL requirements, what jobs it unlocks, and how it fits into the airline career pathway.", href: "/new-zealand/guides/nz-cpl-requirements", time: "7 min read", category: "Training Routes", emoji: "📋" },
  { title: "Best Flight Schools New Zealand 2026", description: "Data-driven comparison of New Zealand's top flight schools — outcomes, costs, fleet, and student reviews.", href: "/new-zealand/guides/best-flight-schools-new-zealand", time: "10 min read", category: "Training Routes", emoji: "🏫" },

  // Medical
  { title: "New Zealand Class 1 Medical", description: "CAA NZ Class 1 medical requirements, what the DAME examines, common disqualifiers, and how to prepare.", href: "/new-zealand/guides/nz-medical-class-1", time: "7 min read", category: "Medical", emoji: "🩺" },

  // Costs & Finance
  { title: "New Zealand Pilot Training Costs 2026", description: "Real cost breakdown for New Zealand pilot training — CAA PPL to ATPL, hour building, and type ratings.", href: "/new-zealand/guides/new-zealand-pilot-training-costs", time: "9 min read", category: "Costs & Finance", emoji: "💰" },

  // Career
  { title: "New Zealand Pilot Salary 2026", description: "Real salary figures for New Zealand first officers and captains at Air New Zealand, Jetstar NZ, and regional carriers.", href: "/new-zealand/guides/new-zealand-pilot-salary-2026", time: "9 min read", category: "Career", emoji: "💵" },
  { title: "New Zealand Regional Airlines Guide", description: "Regional airline careers in New Zealand — Air Nelson, Eagle Air, and the pathway to Air New Zealand.", href: "/new-zealand/guides/new-zealand-regional-airlines-pilot-training", time: "7 min read", category: "Career", emoji: "🗺️" },

  // Cadet Programmes
  { title: "Air New Zealand Cadet Pilot Training", description: "Air New Zealand's cadet programme — how it works, selection, training, and career prospects.", href: "/new-zealand/guides/air-new-zealand-cadet-pilot-training", time: "9 min read", category: "Cadet Programmes", emoji: "🥝" },
  { title: "New Zealand Cadet Programs 2026", description: "Every New Zealand airline cadet and pathway program — eligibility, costs, and how to apply.", href: "/new-zealand/guides/new-zealand-cadet-programs", time: "8 min read", category: "Cadet Programmes", emoji: "🎓" },
],
  },
  'south-africa': {
    label: 'South Africa',
    flag: '🇿🇦',
    regulator: 'SACAA',
    roadmapHref: '/roadmap',
    cadetToolHref: '/tools/cadet-eligibility',
    medicalToolHref: '/tools/class-1-medical-check',
    calculatorHref: '/calculator',
    isThin: true,
    guides: [
  // Getting Started
  { title: "South Africa Pilot Shortage 2026", description: "The real state of the South African pilot shortage — data, causes, and what it means for your career timeline.", href: "/south-africa/guides/south-africa-pilot-shortage", time: "7 min read", category: "Getting Started", emoji: "📊" },

  // Training Routes
  { title: "SA ATPL Requirements", description: "Full breakdown of SACAA ATPL requirements — hours, ratings, knowledge tests, and checkrides.", href: "/south-africa/guides/sa-atpl-requirements", time: "8 min read", category: "Training Routes", emoji: "📋" },
  { title: "SA CPL Requirements", description: "SACAA CPL requirements, what jobs it unlocks, and how it fits into the airline career pathway.", href: "/south-africa/guides/sacpl-requirements", time: "7 min read", category: "Training Routes", emoji: "📋" },
  { title: "Best Flight Schools South Africa 2026", description: "Data-driven comparison of South Africa's top flight schools — outcomes, costs, fleet, and student reviews.", href: "/south-africa/guides/best-flight-schools-south-africa", time: "10 min read", category: "Training Routes", emoji: "🏫" },
  { title: "Military to Airlines in South Africa", description: "How South African military pilots transition to civilian airlines — SAAF pathways, credits, and timelines.", href: "/south-africa/guides/military-to-airlines", time: "8 min read", category: "Training Routes", emoji: "🪖" },

  // Medical
  { title: "SACAA Class 1 Medical Certificate", description: "SACAA Class 1 medical requirements, what the DAME examines, common disqualifiers, and how to prepare.", href: "/south-africa/guides/sacaa-class-1-medical-certificate", time: "7 min read", category: "Medical", emoji: "🩺" },

  // Costs & Finance
  { title: "South Africa Pilot Training Costs 2026", description: "Real cost breakdown for South African pilot training — SACAA PPL to ATPL, hour building, and type ratings.", href: "/south-africa/guides/pilot-training-costs", time: "9 min read", category: "Costs & Finance", emoji: "💰" },

  // Career
  { title: "South Africa Pilot Salary 2026", description: "Real salary figures for South African first officers and captains at SAA, FlySafair, Airlink, and regional carriers.", href: "/south-africa/guides/pilot-salary-2026", time: "9 min read", category: "Career", emoji: "💵" },
  { title: "South Africa Regional Airlines Guide", description: "Regional airline careers in South Africa — Airlink, CemAir, and the pathway to the majors.", href: "/south-africa/guides/south-africa-regional-airlines-pilot-training", time: "7 min read", category: "Career", emoji: "🗺️" },

  // Cadet Programmes
  { title: "South Africa Cadet Programs 2026", description: "Every South African airline cadet and pathway program — eligibility, costs, and how to apply.", href: "/south-africa/guides/south-africa-cadet-programs", time: "8 min read", category: "Cadet Programmes", emoji: "🎓" },
],
  },
  'uae': {
    label: 'UAE',
    flag: '🇦🇪',
    regulator: 'GCAA',
    roadmapHref: '/roadmap',
    cadetToolHref: '/tools/cadet-eligibility',
    medicalToolHref: '/tools/class-1-medical-check',
    calculatorHref: '/calculator',
    isThin: true,
    guides: [
  // Getting Started
  { title: "How to Become a Pilot in the UAE", description: "The complete 2026 guide to GCAA licences, training costs, and the Emirates, Etihad, and Air Arabia cadet pathways.", href: "/uae/guides/how-to-become-a-pilot-uae", time: "10 min read", category: "Getting Started", emoji: "🛫" },
  { title: "UAE Pilot Shortage 2026", description: "The real state of the UAE pilot shortage — data, causes, and what it means for your career timeline.", href: "/uae/guides/uae-pilot-shortage", time: "7 min read", category: "Getting Started", emoji: "📊" },
  { title: "UAE Pilot Lifestyle", description: "What life as a UAE airline pilot actually looks like — rosters, tax-free salary, accommodation, and expat life.", href: "/uae/guides/uae-pilot-lifestyle", time: "7 min read", category: "Getting Started", emoji: "🌅" },

  // Medical
  { title: "UAE GCAA Class 1 Medical", description: "GCAA Class 1 medical requirements, what the AME examines, common disqualifiers, and how to prepare.", href: "/uae/guides/uae-medical-class-1", time: "7 min read", category: "Medical", emoji: "🩺" },

  // Costs & Finance
  { title: "UAE Pilot Training Costs 2026", description: "Real cost breakdown for UAE pilot training — GCAA PPL to ATPL, hour building, and type ratings.", href: "/uae/guides/uae-pilot-training-costs", time: "9 min read", category: "Costs & Finance", emoji: "💰" },

  // Career
  { title: "UAE Pilot Salary 2026", description: "Real salary figures for UAE first officers and captains at Emirates, Etihad, Air Arabia, and flydubai.", href: "/uae/guides/uae-pilot-salary-2026", time: "9 min read", category: "Career", emoji: "💵" },

  // Cadet Programmes
  { title: "Emirates Cadet Pilot Program", description: "Emirates' cadet programme — how it works, selection, training at ECAS, and the guaranteed FO pathway.", href: "/uae/guides/emirates-cadet-pilot-program", time: "10 min read", category: "Cadet Programmes", emoji: "🇦🇪" },
  { title: "Etihad Cadet Pilot Program", description: "Etihad's cadet pathway — how it works, selection, training, and career prospects.", href: "/uae/guides/etihad-cadet-pilot-program", time: "9 min read", category: "Cadet Programmes", emoji: "🟤" },
  { title: "Air Arabia Cadet Program", description: "Air Arabia's cadet programme — how it works, costs, selection, and the regional-to-mainline pathway.", href: "/uae/guides/air-arabia-cadet-program", time: "8 min read", category: "Cadet Programmes", emoji: "🔴" },

  // Flight Schools
  { title: "Best Flight Schools in the UAE 2026", description: "GCAA-approved academies compared — EFTA, Alpha Aviation, Etihad Aviation Training, and Fujairah Aviation Academy.", href: "/uae/guides/best-flight-schools-uae", time: "14 min read", category: "Flight Schools", emoji: "🏫" },
],
  },
};
